// src/lib/players.js
// `goals`    = international goals only (national team)
// `totGoals` = total career goals (club + international, all competitions)
// Stats corrected June 2026 — sources: Transfermarkt, Wikipedia, FotMob, ESPN, messixronaldo.com

export const PLAYERS = [
  { name:'Lionel Messi',       country:'Argentina',  countryCode:'ARG', position:'Forward',    club:'Inter Miami',      age:38, foot:'Left',  flag:'🇦🇷', caps:199, goals:119, totGoals:913,  marketValue:15,  clubs: [{ club: 'Barcelona', years: '2004–2021' }, { club: 'PSG', years: '2021–2023' }, { club: 'Inter Miami', years: '2023–' }] },
  { name:'Lautaro Martinez',   country:'Argentina',  countryCode:'ARG', position:'Forward',    club:'Inter Milan',      age:27, foot:'Right', flag:'🇦🇷', caps:56,  goals:22,  totGoals:170,  marketValue:100, clubs: [{ club: 'Racing Club', years: '2015–2018' }, { club: 'Inter Milan', years: '2018–' }] },
  { name:'Emiliano Martinez',  country:'Argentina',  countryCode:'ARG', position:'Goalkeeper', club:'Aston Villa',      age:32, foot:'Right', flag:'🇦🇷', caps:38,  goals:0,   totGoals:0,    marketValue:25,  clubs: [{ club: 'Arsenal', years: '2012–2020' }, { club: 'Sheffield Wednesday (loan)', years: '2013–2014' }, { club: 'Rotherham United (loan)', years: '2015' }, { club: 'Wolves (loan)', years: '2015–2016' }, { club: 'Getafe (loan)', years: '2017–2018' }, { club: 'Reading (loan)', years: '2019' }, { club: 'Aston Villa', years: '2020–' }] },
  { name:'Kylian Mbappe',      country:'France',     countryCode:'FRA', position:'Forward',    club:'Real Madrid',      age:27, foot:'Right', flag:'🇫🇷', caps:100, goals:58,  totGoals:432,  marketValue:180, clubs: [{ club: 'Monaco', years: '2015–2017' }, { club: 'PSG', years: '2017–2024' }, { club: 'Real Madrid', years: '2024–' }] },
  { name:'Antoine Griezmann',  country:'France',     countryCode:'FRA', position:'Forward',    club:'Atletico Madrid',  age:33, foot:'Left',  flag:'🇫🇷', caps:137, goals:46,  totGoals:280,  marketValue:15,  clubs: [{ club: 'Real Sociedad', years: '2009–2014' }, { club: 'Atletico Madrid', years: '2014–2019' }, { club: 'Barcelona', years: '2019–2021' }, { club: 'Atletico Madrid', years: '2021–' }] },
  { name:'Aurelien Tchouameni',country:'France',     countryCode:'FRA', position:'Midfielder', club:'Real Madrid',      age:25, foot:'Right', flag:'🇫🇷', caps:45,  goals:3,   totGoals:25,   marketValue:80,  clubs: [{ club: 'Monaco', years: '2020–2022' }, { club: 'Real Madrid', years: '2022–' }] },
  { name:'Erling Haaland',     country:'Norway',     countryCode:'NOR', position:'Forward',    club:'Man City',         age:25, foot:'Left',  flag:'🇳🇴', caps:51,  goals:57,  totGoals:354,  marketValue:200, clubs: [{ club: 'Bryne', years: '2015–2016' }, { club: 'Molde', years: '2017–2018' }, { club: 'Red Bull Salzburg', years: '2019' }, { club: 'Borussia Dortmund', years: '2020–2022' }, { club: 'Man City', years: '2022–' }] },
  { name:'Vinicius Jr',        country:'Brazil',     countryCode:'BRA', position:'Forward',    club:'Real Madrid',      age:24, foot:'Right', flag:'🇧🇷', caps:35,  goals:5,   totGoals:155,  marketValue:140, clubs: [{ club: 'Flamengo', years: '2017–2018' }, { club: 'Real Madrid', years: '2018–' }] },
  { name:'Rodrygo',            country:'Brazil',     countryCode:'BRA', position:'Forward',    club:'Real Madrid',      age:24, foot:'Right', flag:'🇧🇷', caps:30,  goals:7,   totGoals:110,  marketValue:90,  clubs: [{ club: 'Santos', years: '2017–2019' }, { club: 'Real Madrid', years: '2019–' }] },
  { name:'Alisson',            country:'Brazil',     countryCode:'BRA', position:'Goalkeeper', club:'Liverpool',        age:32, foot:'Right', flag:'🇧🇷', caps:73,  goals:0,   totGoals:1,    marketValue:25,  clubs: [{ club: 'Internacional', years: '2013–2016' }, { club: 'Roma', years: '2016–2018' }, { club: 'Liverpool', years: '2018–' }] },
  { name:'Marquinhos',         country:'Brazil',     countryCode:'BRA', position:'Defender',   club:'PSG',              age:30, foot:'Right', flag:'🇧🇷', caps:92,  goals:7,   totGoals:45,   marketValue:40,  clubs: [{ club: 'Corinthians', years: '2011–2012' }, { club: 'Roma', years: '2012–2013' }, { club: 'PSG', years: '2013–' }] },
  { name:'Casemiro',           country:'Brazil',     countryCode:'BRA', position:'Midfielder', club:'Man United',       age:32, foot:'Right', flag:'🇧🇷', caps:85,  goals:7,   totGoals:60,   marketValue:15,  clubs: [{ club: 'Sao Paulo', years: '2010–2013' }, { club: 'Real Madrid', years: '2013–2022' }, { club: 'Porto (loan)', years: '2014–2015' }, { club: 'Man United', years: '2022–' }] },
  { name:'Jude Bellingham',    country:'England',    countryCode:'ENG', position:'Midfielder', club:'Real Madrid',      age:22, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:49,  goals:5,   totGoals:95,   marketValue:130, clubs: [{ club: 'Birmingham City', years: '2019–2020' }, { club: 'Borussia Dortmund', years: '2020–2023' }, { club: 'Real Madrid', years: '2023–' }] },
  { name:'Harry Kane',         country:'England',    countryCode:'ENG', position:'Forward',    club:'Bayern Munich',    age:32, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:112, goals:78,  totGoals:532,  marketValue:90,  clubs: [{ club: 'Tottenham', years: '2009–2023' }, { club: 'Leyton Orient (loan)', years: '2011' }, { club: 'Millwall (loan)', years: '2012' }, { club: 'Norwich City (loan)', years: '2012–2013' }, { club: 'Leicester City (loan)', years: '2013' }, { club: 'Bayern Munich', years: '2023–' }] },
  { name:'Bukayo Saka',        country:'England',    countryCode:'ENG', position:'Forward',    club:'Arsenal',          age:24, foot:'Left',  flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:50,  goals:14,  totGoals:115,  marketValue:120, clubs: [{ club: 'Arsenal', years: '2018–' }] },
  { name:'Phil Foden',         country:'England',    countryCode:'ENG', position:'Midfielder', club:'Man City',         age:25, foot:'Left',  flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:44,  goals:6,   totGoals:115,  marketValue:120, clubs: [{ club: 'Man City', years: '2017–' }] },
  { name:'Declan Rice',        country:'England',    countryCode:'ENG', position:'Midfielder', club:'Arsenal',          age:26, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:58,  goals:3,   totGoals:40,   marketValue:90,  clubs: [{ club: 'West Ham', years: '2017–2023' }, { club: 'Arsenal', years: '2023–' }] },
  { name:'Robert Lewandowski', country:'Poland',     countryCode:'POL', position:'Forward',    club:'Barcelona',        age:36, foot:'Right', flag:'🇵🇱', caps:152, goals:84,  totGoals:685,  marketValue:12,  clubs: [{ club: 'Znicz Pruszkow', years: '2006–2008' }, { club: 'Lech Poznan', years: '2008–2010' }, { club: 'Borussia Dortmund', years: '2010–2014' }, { club: 'Bayern Munich', years: '2014–2022' }, { club: 'Barcelona', years: '2022–' }] },
  { name:'Pedri',              country:'Spain',      countryCode:'ESP', position:'Midfielder', club:'Barcelona',        age:22, foot:'Right', flag:'🇪🇸', caps:35,  goals:4,   totGoals:42,   marketValue:150, clubs: [{ club: 'Las Palmas', years: '2019–2020' }, { club: 'Barcelona', years: '2020–' }] },
  { name:'Gavi',               country:'Spain',      countryCode:'ESP', position:'Midfielder', club:'Barcelona',        age:20, foot:'Left',  flag:'🇪🇸', caps:42,  goals:7,   totGoals:28,   marketValue:80,  clubs: [{ club: 'Barcelona', years: '2021–' }] },
  { name:'Lamine Yamal',       country:'Spain',      countryCode:'ESP', position:'Forward',    club:'Barcelona',        age:18, foot:'Right', flag:'🇪🇸', caps:28,  goals:8,   totGoals:42,   marketValue:200, clubs: [{ club: 'Barcelona', years: '2023–' }] },
  { name:'Alvaro Morata',      country:'Spain',      countryCode:'ESP', position:'Forward',    club:'AC Milan',         age:32, foot:'Right', flag:'🇪🇸', caps:76,  goals:34,  totGoals:205,  marketValue:10,  clubs: [{ club: 'Real Madrid', years: '2010–2014' }, { club: 'Juventus', years: '2014–2016' }, { club: 'Real Madrid', years: '2016–2017' }, { club: 'Chelsea', years: '2017–2020' }, { club: 'Atletico Madrid', years: '2019–2024' }, { club: 'AC Milan', years: '2024–' }] },
  { name:'Rodri',              country:'Spain',      countryCode:'ESP', position:'Midfielder', club:'Man City',         age:28, foot:'Right', flag:'🇪🇸', caps:60,  goals:5,   totGoals:40,   marketValue:120, clubs: [{ club: 'Villarreal', years: '2015–2018' }, { club: 'Atletico Madrid', years: '2018–2019' }, { club: 'Man City', years: '2019–' }] },
  { name:'Jamal Musiala',      country:'Germany',    countryCode:'GER', position:'Midfielder', club:'Bayern Munich',    age:22, foot:'Right', flag:'🇩🇪', caps:44,  goals:8,   totGoals:75,   marketValue:120, clubs: [{ club: 'Bayern Munich', years: '2020–' }] },
  { name:'Florian Wirtz',      country:'Germany',    countryCode:'GER', position:'Midfielder', club:'Bayer Leverkusen', age:21, foot:'Left',  flag:'🇩🇪', caps:30,  goals:5,   totGoals:65,   marketValue:120, clubs: [{ club: 'Bayer Leverkusen', years: '2020–' }] },
  { name:'Manuel Neuer',       country:'Germany',    countryCode:'GER', position:'Goalkeeper', club:'Bayern Munich',    age:40, foot:'Right', flag:'🇩🇪', caps:124, goals:0,   totGoals:0,    marketValue:3,   clubs: [{ club: 'Schalke 04', years: '2006–2011' }, { club: 'Bayern Munich', years: '2011–' }] },
  { name:'Leroy Sane',         country:'Germany',    countryCode:'GER', position:'Forward',    club:'Bayern Munich',    age:30, foot:'Right', flag:'🇩🇪', caps:64,  goals:14,  totGoals:155,  marketValue:40,  clubs: [{ club: 'Schalke 04', years: '2014–2016' }, { club: 'Man City', years: '2016–2020' }, { club: 'Bayern Munich', years: '2020–' }] },
  { name:'Joao Felix',         country:'Portugal',   countryCode:'POR', position:'Forward',    club:'Chelsea',          age:25, foot:'Right', flag:'🇵🇹', caps:46,  goals:9,   totGoals:95,   marketValue:30,  clubs: [{ club: 'Benfica', years: '2018–2019' }, { club: 'Atletico Madrid', years: '2019–' }, { club: 'Chelsea (loan)', years: '2023' }, { club: 'Barcelona (loan)', years: '2023–2024' }, { club: 'Chelsea', years: '2024–' }] },
  { name:'Bruno Fernandes',    country:'Portugal',   countryCode:'POR', position:'Midfielder', club:'Man United',       age:30, foot:'Right', flag:'🇵🇹', caps:76,  goals:22,  totGoals:145,  marketValue:60,  clubs: [{ club: 'Novara', years: '2012–2013' }, { club: 'Udinese', years: '2013–2016' }, { club: 'Sampdoria', years: '2016–2017' }, { club: 'Sporting CP', years: '2017–2020' }, { club: 'Man United', years: '2020–' }] },
  { name:'Ruben Dias',         country:'Portugal',   countryCode:'POR', position:'Defender',   club:'Man City',         age:27, foot:'Right', flag:'🇵🇹', caps:65,  goals:3,   totGoals:12,   marketValue:70,  clubs: [{ club: 'Benfica', years: '2017–2020' }, { club: 'Man City', years: '2020–' }] },
  { name:'Cristiano Ronaldo',  country:'Portugal',   countryCode:'POR', position:'Forward',    club:'Al Nassr',         age:41, foot:'Right', flag:'🇵🇹', caps:228, goals:143, totGoals:971,  marketValue:10,  clubs: [{ club: 'Sporting CP', years: '2002–2003' }, { club: 'Man United', years: '2003–2009' }, { club: 'Real Madrid', years: '2009–2018' }, { club: 'Juventus', years: '2018–2021' }, { club: 'Man United', years: '2021–2022' }, { club: 'Al Nassr', years: '2023–' }] },
  { name:'Raphinha',           country:'Brazil',     countryCode:'BRA', position:'Forward',    club:'Barcelona',        age:28, foot:'Left',  flag:'🇧🇷', caps:36,  goals:9,   totGoals:145,  marketValue:45,  clubs: [{ club: 'Vitoria Guimaraes', years: '2016–2018' }, { club: 'Sporting CP', years: '2018–2019' }, { club: 'Rennes', years: '2019–2020' }, { club: 'Leeds', years: '2020–2022' }, { club: 'Barcelona', years: '2022–' }] },
  { name:'Achraf Hakimi',      country:'Morocco',    countryCode:'MAR', position:'Defender',   club:'PSG',              age:26, foot:'Right', flag:'🇲🇦', caps:82,  goals:11,  totGoals:65,   marketValue:65,  clubs: [{ club: 'Real Madrid', years: '2017–2020' }, { club: 'Borussia Dortmund (loan)', years: '2018–2020' }, { club: 'Inter Milan', years: '2020–2021' }, { club: 'PSG', years: '2021–' }] },
  { name:'Hakim Ziyech',       country:'Morocco',    countryCode:'MAR', position:'Midfielder', club:'Galatasaray',      age:31, foot:'Left',  flag:'🇲🇦', caps:63,  goals:22,  totGoals:135,  marketValue:8,   clubs: [{ club: 'Heerenveen', years: '2012–2014' }, { club: 'Twente', years: '2014–2016' }, { club: 'Ajax', years: '2016–2020' }, { club: 'Chelsea', years: '2020–2024' }, { club: 'Galatasaray', years: '2023–' }] },
  { name:'Yassine Bounou',     country:'Morocco',    countryCode:'MAR', position:'Goalkeeper', club:'Al Hilal',         age:33, foot:'Right', flag:'🇲🇦', caps:68,  goals:0,   totGoals:0,    marketValue:8,   clubs: [{ club: 'Wydad AC', years: '2010–2012' }, { club: 'Atletico Madrid', years: '2012–2016' }, { club: 'Zaragoza (loan)', years: '2014–2016' }, { club: 'Girona', years: '2016–2019' }, { club: 'Sevilla', years: '2019–2023' }, { club: 'Al Hilal', years: '2023–' }] },
  { name:'Victor Osimhen',     country:'Nigeria',    countryCode:'NGA', position:'Forward',    club:'Galatasaray',      age:26, foot:'Right', flag:'🇳🇬', caps:35,  goals:24,  totGoals:170,  marketValue:70,  clubs: [{ club: 'Wolfsburg', years: '2017–2019' }, { club: 'Charleroi', years: '2018–2019' }, { club: 'Lille', years: '2019–2020' }, { club: 'Napoli', years: '2020–' }, { club: 'Galatasaray (loan)', years: '2024–' }] },
  { name:'Sadio Mane',         country:'Senegal',    countryCode:'SEN', position:'Forward',    club:'Al Nassr',         age:33, foot:'Right', flag:'🇸🇳', caps:105, goals:44,  totGoals:270,  marketValue:12,  clubs: [{ club: 'Metz', years: '2011–2012' }, { club: 'Red Bull Salzburg', years: '2012–2014' }, { club: 'Southampton', years: '2014–2016' }, { club: 'Liverpool', years: '2016–2022' }, { club: 'Bayern Munich', years: '2022–2023' }, { club: 'Al Nassr', years: '2023–' }] },
  { name:'Mohamed Salah',      country:'Egypt',      countryCode:'EGY', position:'Forward',    club:'Liverpool',        age:32, foot:'Left',  flag:'🇪🇬', caps:104, goals:60,  totGoals:340,  marketValue:50,  clubs: [{ club: 'El Mokawloon', years: '2010–2012' }, { club: 'Basel', years: '2012–2014' }, { club: 'Chelsea', years: '2014–2016' }, { club: 'Fiorentina (loan)', years: '2015' }, { club: 'Roma', years: '2015–2017' }, { club: 'Liverpool', years: '2017–' }] },
  { name:'Son Heung-min',      country:'South Korea',countryCode:'KOR', position:'Forward',    club:'Tottenham',        age:33, foot:'Right', flag:'🇰🇷', caps:135, goals:48,  totGoals:290,  marketValue:35,  clubs: [{ club: 'Hamburger SV', years: '2010–2013' }, { club: 'Bayer Leverkusen', years: '2013–2015' }, { club: 'Tottenham', years: '2015–' }] },
  { name:'Takumi Minamino',    country:'Japan',      countryCode:'JPN', position:'Midfielder', club:'Monaco',           age:29, foot:'Right', flag:'🇯🇵', caps:63,  goals:22,  totGoals:115,  marketValue:12,  clubs: [{ club: 'Cerezo Osaka', years: '2012–2014' }, { club: 'Red Bull Salzburg', years: '2015–2020' }, { club: 'Liverpool', years: '2020–2022' }, { club: 'Southampton (loan)', years: '2021' }, { club: 'Monaco', years: '2022–' }] },
  { name:'Ritsu Doan',         country:'Japan',      countryCode:'JPN', position:'Forward',    club:'Freiburg',         age:26, foot:'Right', flag:'🇯🇵', caps:55,  goals:9,   totGoals:75,   marketValue:16,  clubs: [{ club: 'Gamba Osaka', years: '2015–2018' }, { club: 'Groningen', years: '2017–2019' }, { club: 'PSV', years: '2019–2022' }, { club: 'Arminia Bielefeld (loan)', years: '2020–2021' }, { club: 'Freiburg', years: '2022–' }] },
  { name:'Ivan Perisic',       country:'Croatia',    countryCode:'CRO', position:'Midfielder', club:'Hajduk Split',     age:35, foot:'Left',  flag:'🇭🇷', caps:135, goals:34,  totGoals:230,  marketValue:3,   clubs: [{ club: 'Club Brugge', years: '2009–2011' }, { club: 'Borussia Dortmund', years: '2011–2013' }, { club: 'Wolfsburg', years: '2013–2015' }, { club: 'Inter Milan', years: '2015–2022' }, { club: 'Bayern Munich (loan)', years: '2019–2020' }, { club: 'Tottenham', years: '2022–2024' }, { club: 'Hajduk Split', years: '2024–' }] },
  { name:'Luka Modric',        country:'Croatia',    countryCode:'CRO', position:'Midfielder', club:'Real Madrid',      age:40, foot:'Right', flag:'🇭🇷', caps:180, goals:25,  totGoals:120,  marketValue:5,   clubs: [{ club: 'Dinamo Zagreb', years: '2003–2008' }, { club: 'Zrinjski Mostar (loan)', years: '2003–2004' }, { club: 'Inter Zapresic (loan)', years: '2004–2005' }, { club: 'Tottenham', years: '2008–2012' }, { club: 'Real Madrid', years: '2012–' }] },
  { name:'Dominik Livakovic',  country:'Croatia',    countryCode:'CRO', position:'Goalkeeper', club:'Fenerbahce',       age:29, foot:'Right', flag:'🇭🇷', caps:60,  goals:0,   totGoals:0,    marketValue:12,  clubs: [{ club: 'Zagreb', years: '2012–2015' }, { club: 'Dinamo Zagreb', years: '2015–2023' }, { club: 'Fenerbahce', years: '2023–' }] },
  { name:'Memphis Depay',      country:'Netherlands',countryCode:'NED', position:'Forward',    club:'Corinthians',      age:30, foot:'Right', flag:'🇳🇱', caps:96,  goals:45,  totGoals:270,  marketValue:5,   clubs: [{ club: 'PSV', years: '2011–2015' }, { club: 'Man United', years: '2015–2017' }, { club: 'Lyon', years: '2017–2021' }, { club: 'Barcelona', years: '2021–2023' }, { club: 'Atletico Madrid', years: '2023–2024' }, { club: 'Corinthians', years: '2024–' }] },
  { name:'Virgil van Dijk',    country:'Netherlands',countryCode:'NED', position:'Defender',   club:'Liverpool',        age:34, foot:'Right', flag:'🇳🇱', caps:75,  goals:7,   totGoals:40,   marketValue:25,  clubs: [{ club: 'Groningen', years: '2011–2013' }, { club: 'Celtic', years: '2013–2015' }, { club: 'Southampton', years: '2015–2018' }, { club: 'Liverpool', years: '2018–' }] },
  { name:'Cody Gakpo',         country:'Netherlands',countryCode:'NED', position:'Forward',    club:'Liverpool',        age:25, foot:'Right', flag:'🇳🇱', caps:35,  goals:13,  totGoals:90,   marketValue:55,  clubs: [{ club: 'PSV', years: '2018–2023' }, { club: 'Liverpool', years: '2023–' }] },
  { name:'Frenkie de Jong',    country:'Netherlands',countryCode:'NED', position:'Midfielder', club:'Barcelona',        age:28, foot:'Right', flag:'🇳🇱', caps:62,  goals:3,   totGoals:30,   marketValue:70,  clubs: [{ club: 'Willem II', years: '2015' }, { club: 'Ajax', years: '2015–2019' }, { club: 'Barcelona', years: '2019–' }] },
  { name:'Christian Pulisic',  country:'USA',        countryCode:'USA', position:'Forward',    club:'AC Milan',         age:26, foot:'Right', flag:'🇺🇸', caps:75,  goals:32,  totGoals:155,  marketValue:35,  clubs: [{ club: 'Borussia Dortmund', years: '2016–2019' }, { club: 'Chelsea', years: '2019–2023' }, { club: 'AC Milan', years: '2023–' }] },
  { name:'Alphonso Davies',    country:'Canada',     countryCode:'CAN', position:'Defender',   club:'Bayern Munich',    age:25, foot:'Left',  flag:'🇨🇦', caps:55,  goals:17,  totGoals:28,   marketValue:55,  clubs: [{ club: 'Vancouver Whitecaps', years: '2016–2018' }, { club: 'Bayern Munich', years: '2019–' }] },
  { name:'Jonathan David',     country:'Canada',     countryCode:'CAN', position:'Forward',    club:'Lille',            age:25, foot:'Right', flag:'🇨🇦', caps:55,  goals:32,  totGoals:195,  marketValue:60,  clubs: [{ club: 'Gent', years: '2018–2020' }, { club: 'Lille', years: '2020–' }] },
  { name:'Hirving Lozano',     country:'Mexico',     countryCode:'MEX', position:'Forward',    club:'PSV',              age:29, foot:'Right', flag:'🇲🇽', caps:80,  goals:21,  totGoals:155,  marketValue:15,  clubs: [{ club: 'Pachuca', years: '2014–2017' }, { club: 'PSV', years: '2017–2019' }, { club: 'Napoli', years: '2019–2023' }, { club: 'PSV', years: '2023–' }] },
  { name:'Edson Alvarez',      country:'Mexico',     countryCode:'MEX', position:'Midfielder', club:'West Ham',         age:27, foot:'Right', flag:'🇲🇽', caps:82,  goals:6,   totGoals:30,   marketValue:30,  clubs: [{ club: 'America', years: '2016–2019' }, { club: 'Ajax', years: '2019–2023' }, { club: 'West Ham', years: '2023–' }] },
  { name:'Paulo Dybala',       country:'Argentina',  countryCode:'ARG', position:'Forward',    club:'Roma',             age:31, foot:'Left',  flag:'🇦🇷', caps:38,  goals:3,   totGoals:210,  marketValue:18,  clubs: [{ club: 'Instituto', years: '2011–2012' }, { club: 'Palermo', years: '2012–2015' }, { club: 'Juventus', years: '2015–2022' }, { club: 'Roma', years: '2022–' }] },
  { name:'Julian Alvarez',     country:'Argentina',  countryCode:'ARG', position:'Forward',    club:'Atletico Madrid',  age:25, foot:'Right', flag:'🇦🇷', caps:45,  goals:18,  totGoals:140,  marketValue:100, clubs: [{ club: 'River Plate', years: '2018–2022' }, { club: 'Man City', years: '2022–2024' }, { club: 'Atletico Madrid', years: '2024–' }] },
  { name:'Darwin Nunez',       country:'Uruguay',    countryCode:'URU', position:'Forward',    club:'Liverpool',        age:25, foot:'Right', flag:'🇺🇾', caps:35,  goals:14,  totGoals:130,  marketValue:65,  clubs: [{ club: 'Penarol', years: '2017–2019' }, { club: 'Almeria', years: '2019–2020' }, { club: 'Benfica', years: '2020–2022' }, { club: 'Liverpool', years: '2022–' }] },
  { name:'Federico Valverde',  country:'Uruguay',    countryCode:'URU', position:'Midfielder', club:'Real Madrid',      age:26, foot:'Right', flag:'🇺🇾', caps:68,  goals:10,  totGoals:55,   marketValue:100, clubs: [{ club: 'Penarol', years: '2015–2016' }, { club: 'Real Madrid', years: '2016–' }, { club: 'Deportivo La Coruna (loan)', years: '2017–2018' }] },
  { name:'Luis Diaz',          country:'Colombia',   countryCode:'COL', position:'Forward',    club:'Liverpool',        age:28, foot:'Right', flag:'🇨🇴', caps:60,  goals:14,  totGoals:115,  marketValue:70,  clubs: [{ club: 'Junior', years: '2017–2019' }, { club: 'Porto', years: '2019–2022' }, { club: 'Liverpool', years: '2022–' }] },
  { name:'James Rodriguez',    country:'Colombia',   countryCode:'COL', position:'Midfielder', club:'Rayo Vallecano',   age:33, foot:'Right', flag:'🇨🇴', caps:100, goals:29,  totGoals:165,  marketValue:4,   clubs: [{ club: 'Envigado', years: '2006–2008' }, { club: 'Banfield', years: '2008–2010' }, { club: 'Porto', years: '2010–2013' }, { club: 'Monaco', years: '2013–2014' }, { club: 'Real Madrid', years: '2014–2020' }, { club: 'Bayern Munich (loan)', years: '2017–2019' }, { club: 'Everton', years: '2020–2021' }, { club: 'Al Rayyan', years: '2021–2022' }, { club: 'Olympiacos', years: '2022–2023' }, { club: 'Sao Paulo', years: '2023–2024' }, { club: 'Rayo Vallecano', years: '2024–' }] },
  { name:'Alexis Mac Allister', country:'Argentina', countryCode:'ARG', position:'Midfielder', club:'Liverpool',        age:26, foot:'Right', flag:'🇦🇷', caps:36,  goals:5,   totGoals:65,   marketValue:75,  clubs: [{ club: 'Argentinos Juniors', years: '2016–2019' }, { club: 'Brighton', years: '2019–2023' }, { club: 'Boca Juniors (loan)', years: '2019' }, { club: 'Liverpool', years: '2023–' }] },
  { name:'Granit Xhaka',       country:'Switzerland',countryCode:'CHE', position:'Midfielder', club:'Bayer Leverkusen', age:32, foot:'Left',  flag:'🇨🇭', caps:130, goals:15,  totGoals:75,   marketValue:18,  clubs: [{ club: 'Basel', years: '2010–2012' }, { club: 'Borussia Monchengladbach', years: '2012–2016' }, { club: 'Arsenal', years: '2016–2023' }, { club: 'Bayer Leverkusen', years: '2023–' }] },
  { name:'Xherdan Shaqiri',    country:'Switzerland',countryCode:'CHE', position:'Midfielder', club:'Basel',            age:33, foot:'Right', flag:'🇨🇭', caps:125, goals:32,  totGoals:175,  marketValue:2,   clubs: [{ club: 'Basel', years: '2009–2012' }, { club: 'Bayern Munich', years: '2012–2015' }, { club: 'Inter Milan', years: '2015' }, { club: 'Stoke City', years: '2015–2018' }, { club: 'Liverpool', years: '2018–2021' }, { club: 'Lyon', years: '2021–2022' }, { club: 'Chicago Fire', years: '2022–2024' }, { club: 'Basel', years: '2024–' }] },
  { name:'Romelu Lukaku',      country:'Belgium',    countryCode:'BEL', position:'Forward',    club:'Napoli',           age:31, foot:'Right', flag:'🇧🇪', caps:118, goals:87,  totGoals:370,  marketValue:25,  clubs: [{ club: 'Anderlecht', years: '2009–2011' }, { club: 'Chelsea', years: '2011–2014' }, { club: 'West Brom (loan)', years: '2012–2013' }, { club: 'Everton', years: '2013–2017' }, { club: 'Manchester United', years: '2017–2019' }, { club: 'Inter Milan', years: '2019–2021' }, { club: 'Chelsea', years: '2021–' }, { club: 'Inter Milan (loan)', years: '2022–2023' }, { club: 'Roma (loan)', years: '2023–2024' }, { club: 'Napoli', years: '2024–' }] },
  { name:'Kevin De Bruyne',    country:'Belgium',    countryCode:'BEL', position:'Midfielder', club:'Man City',         age:34, foot:'Right', flag:'🇧🇪', caps:106, goals:27,  totGoals:135,  marketValue:40,  clubs: [{ club: 'Genk', years: '2008–2012' }, { club: 'Chelsea', years: '2012–2014' }, { club: 'Werder Bremen (loan)', years: '2012–2013' }, { club: 'VfL Wolfsburg', years: '2014–2015' }, { club: 'Man City', years: '2015–' }] },
  { name:'Thibaut Courtois',   country:'Belgium',    countryCode:'BEL', position:'Goalkeeper', club:'Real Madrid',      age:32, foot:'Right', flag:'🇧🇪', caps:105, goals:0,   totGoals:0,    marketValue:30,  clubs: [{ club: 'Genk', years: '2009–2011' }, { club: 'Chelsea', years: '2011–2018' }, { club: 'Atletico Madrid (loan)', years: '2011–2014' }, { club: 'Real Madrid', years: '2018–' }] },
  { name:'Rafael Leao',        country:'Portugal',   countryCode:'POR', position:'Forward',    club:'AC Milan',         age:25, foot:'Right', flag:'🇵🇹', caps:38,  goals:7,   totGoals:80,   marketValue:80,  clubs: [{ club: 'Sporting CP', years: '2017–2018' }, { club: 'Lille', years: '2018–2019' }, { club: 'AC Milan', years: '2019–' }] },
  { name:'Bernardo Silva',     country:'Portugal',   countryCode:'POR', position:'Midfielder', club:'Man City',         age:30, foot:'Left',  flag:'🇵🇹', caps:100, goals:12,  totGoals:90,   marketValue:70,  clubs: [{ club: 'Benfica', years: '2013–2015' }, { club: 'Monaco', years: '2014–2017' }, { club: 'Man City', years: '2017–' }] },
  { name:'Josko Gvardiol',     country:'Croatia',    countryCode:'CRO', position:'Defender',   club:'Man City',         age:23, foot:'Left',  flag:'🇭🇷', caps:42,  goals:4,   totGoals:18,   marketValue:75,  clubs: [{ club: 'Dinamo Zagreb', years: '2019–2021' }, { club: 'RB Leipzig', years: '2021–2023' }, { club: 'Man City', years: '2023–' }] },
  { name:'Mateo Kovacic',      country:'Croatia',    countryCode:'CRO', position:'Midfielder', club:'Man City',         age:31, foot:'Right', flag:'🇭🇷', caps:105, goals:5,   totGoals:38,   marketValue:25,  clubs: [{ club: 'Dinamo Zagreb', years: '2010–2013' }, { club: 'Inter Milan', years: '2013–2015' }, { club: 'Real Madrid', years: '2015–2019' }, { club: 'Chelsea', years: '2018–2023' }, { club: 'Man City', years: '2023–' }] },
  { name:'Angel Di Maria',     country:'Argentina',  countryCode:'ARG', position:'Forward',    club:'Benfica',          age:37, foot:'Left',  flag:'🇦🇷', caps:145, goals:31,  totGoals:250,  marketValue:3,   clubs: [{ club: 'Rosario Central', years: '2005–2007' }, { club: 'Benfica', years: '2007–2010' }, { club: 'Real Madrid', years: '2010–2014' }, { club: 'Manchester United', years: '2014–2015' }, { club: 'PSG', years: '2015–2022' }, { club: 'Juventus', years: '2022–2023' }, { club: 'Benfica', years: '2023–' }] },
  { name:'Rodrigo De Paul',    country:'Argentina',  countryCode:'ARG', position:'Midfielder', club:'Atletico Madrid',  age:30, foot:'Right', flag:'🇦🇷', caps:72,  goals:4,   totGoals:65,   marketValue:25,  clubs: [{ club: 'Racing Club', years: '2012–2014' }, { club: 'Valencia', years: '2014–2016' }, { club: 'Udinese', years: '2016–2021' }, { club: 'Atletico Madrid', years: '2021–' }] },
  { name:'Enzo Fernandez',     country:'Argentina',  countryCode:'ARG', position:'Midfielder', club:'Chelsea',          age:24, foot:'Right', flag:'🇦🇷', caps:32,  goals:5,   totGoals:35,   marketValue:75,  clubs: [{ club: 'River Plate', years: '2019–2022' }, { club: 'Benfica', years: '2022–2023' }, { club: 'Chelsea', years: '2023–' }] },
  { name:'Cristian Romero',    country:'Argentina',  countryCode:'ARG', position:'Defender',   club:'Tottenham',        age:26, foot:'Right', flag:'🇦🇷', caps:38,  goals:2,   totGoals:12,   marketValue:55,  clubs: [{ club: 'Belgrano', years: '2016–2018' }, { club: 'Genoa', years: '2018–2020' }, { club: 'Atalanta (loan)', years: '2020–2021' }, { club: 'Tottenham', years: '2021–' }] },
  { name:'Ousmane Dembele',    country:'France',     countryCode:'FRA', position:'Forward',    club:'PSG',              age:27, foot:'Right', flag:'🇫🇷', caps:58,  goals:8,   totGoals:155,  marketValue:55,  clubs: [{ club: 'Rennes', years: '2015–2016' }, { club: 'Borussia Dortmund', years: '2016–2017' }, { club: 'Barcelona', years: '2017–2023' }, { club: 'PSG', years: '2023–' }] },
  { name:'Theo Hernandez',     country:'France',     countryCode:'FRA', position:'Defender',   club:'AC Milan',         age:27, foot:'Left',  flag:'🇫🇷', caps:42,  goals:4,   totGoals:45,   marketValue:55,  clubs: [{ club: 'Atletico Madrid', years: '2016–2017' }, { club: 'Real Madrid', years: '2017–2019' }, { club: 'Real Sociedad (loan)', years: '2018–2019' }, { club: 'AC Milan', years: '2019–' }] },
  { name:'Olivier Giroud',     country:'France',     countryCode:'FRA', position:'Forward',    club:'LAFC',             age:39, foot:'Left',  flag:'🇫🇷', caps:135, goals:57,  totGoals:380,  marketValue:2,   clubs: [{ club: 'Grenoble', years: '2005–2008' }, { club: 'Tours', years: '2008–2010' }, { club: 'Montpellier', years: '2010–2012' }, { club: 'Arsenal', years: '2012–2018' }, { club: 'Chelsea', years: '2018–2021' }, { club: 'AC Milan', years: '2021–2024' }, { club: 'LAFC', years: '2024–' }] },
  { name:'Mike Maignan',       country:'France',     countryCode:'FRA', position:'Goalkeeper', club:'AC Milan',         age:29, foot:'Right', flag:'🇫🇷', caps:28,  goals:0,   totGoals:0,    marketValue:40,  clubs: [{ club: 'Lille', years: '2015–2021' }, { club: 'AC Milan', years: '2021–' }] },
  { name:'Marcus Rashford',    country:'England',    countryCode:'ENG', position:'Forward',    club:'Barcelona',        age:28, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:68,  goals:18,  totGoals:155,  marketValue:40,  clubs: [{ club: 'Man United', years: '2015–2025' }, { club: 'Barcelona (loan)', years: '2025–' }] },
  { name:'John Stones',        country:'England',    countryCode:'ENG', position:'Defender',   club:'Man City',         age:31, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:78,  goals:3,   totGoals:15,   marketValue:28,  clubs: [{ club: 'Barnsley', years: '2011–2013' }, { club: 'Everton', years: '2013–2016' }, { club: 'Man City', years: '2016–' }] },
  { name:'Jordan Pickford',    country:'England',    countryCode:'ENG', position:'Goalkeeper', club:'Everton',          age:32, foot:'Left',  flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:72,  goals:0,   totGoals:0,    marketValue:18,  clubs: [{ club: 'Sunderland', years: '2011–2017' }, { club: 'Everton', years: '2017–' }] },
  { name:'Kyle Walker',        country:'England',    countryCode:'ENG', position:'Defender',   club:'Man City',         age:35, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:85,  goals:1,   totGoals:8,    marketValue:8,   clubs: [{ club: 'Sheffield United', years: '2008–2009' }, { club: 'Tottenham', years: '2009–2017' }, { club: 'Man City', years: '2017–' }] },
  { name:'Nico Williams',      country:'Spain',      countryCode:'ESP', position:'Forward',    club:'Athletic Bilbao',  age:22, foot:'Right', flag:'🇪🇸', caps:24,  goals:5,   totGoals:48,   marketValue:80,  clubs: [{ club: 'Athletic Bilbao', years: '2020–' }] },
  { name:'Dani Olmo',          country:'Spain',      countryCode:'ESP', position:'Midfielder', club:'Barcelona',        age:26, foot:'Right', flag:'🇪🇸', caps:44,  goals:12,  totGoals:85,   marketValue:60,  clubs: [{ club: 'Dinamo Zagreb', years: '2015–2020' }, { club: 'RB Leipzig', years: '2020–2024' }, { club: 'Barcelona', years: '2024–' }] },
  { name:'Dani Carvajal',      country:'Spain',      countryCode:'ESP', position:'Defender',   club:'Real Madrid',      age:33, foot:'Right', flag:'🇪🇸', caps:50,  goals:1,   totGoals:12,   marketValue:10,  clubs: [{ club: 'Bayer Leverkusen', years: '2012–2013' }, { club: 'Real Madrid', years: '2013–' }] },
  { name:'Unai Simon',         country:'Spain',      countryCode:'ESP', position:'Goalkeeper', club:'Athletic Bilbao',  age:27, foot:'Right', flag:'🇪🇸', caps:50,  goals:0,   totGoals:0,    marketValue:28,  clubs: [{ club: 'Athletic Bilbao', years: '2018–' }] },
  { name:'Ilkay Gundogan',     country:'Germany',    countryCode:'GER', position:'Midfielder', club:'Man City',         age:35, foot:'Right', flag:'🇩🇪', caps:75,  goals:18,  totGoals:115,  marketValue:8,   clubs: [{ club: 'Nurnberg', years: '2009–2011' }, { club: 'Borussia Dortmund', years: '2011–2016' }, { club: 'Man City', years: '2016–2023' }, { club: 'Barcelona', years: '2023–2024' }, { club: 'Man City', years: '2024–' }] },
  { name:'Kai Havertz',        country:'Germany',    countryCode:'GER', position:'Forward',    club:'Arsenal',          age:26, foot:'Left',  flag:'🇩🇪', caps:54,  goals:18,  totGoals:110,  marketValue:70,  clubs: [{ club: 'Bayer Leverkusen', years: '2016–2020' }, { club: 'Chelsea', years: '2020–2023' }, { club: 'Arsenal', years: '2023–' }] },
  { name:'Joshua Kimmich',     country:'Germany',    countryCode:'GER', position:'Midfielder', club:'Bayern Munich',    age:31, foot:'Right', flag:'🇩🇪', caps:90,  goals:7,   totGoals:55,   marketValue:55,  clubs: [{ club: 'RB Leipzig', years: '2013–2015' }, { club: 'Bayern Munich', years: '2015–' }] },
  { name:'Antonio Rudiger',    country:'Germany',    countryCode:'GER', position:'Defender',   club:'Real Madrid',      age:33, foot:'Right', flag:'🇩🇪', caps:78,  goals:4,   totGoals:25,   marketValue:22,  clubs: [{ club: 'VfB Stuttgart', years: '2012–2016' }, { club: 'Roma', years: '2015–2017' }, { club: 'Chelsea', years: '2017–2022' }, { club: 'Real Madrid', years: '2022–' }] },
  { name:'Weston McKennie',    country:'USA',        countryCode:'USA', position:'Midfielder', club:'Juventus',         age:26, foot:'Right', flag:'🇺🇸', caps:58,  goals:13,  totGoals:45,   marketValue:25,  clubs: [{ club: 'Schalke 04', years: '2017–2021' }, { club: 'Juventus', years: '2020–' }, { club: 'Leeds (loan)', years: '2023' }] },
  { name:'Tyler Adams',        country:'USA',        countryCode:'USA', position:'Midfielder', club:'Bournemouth',      age:26, foot:'Right', flag:'🇺🇸', caps:45,  goals:2,   totGoals:8,    marketValue:12,  clubs: [{ club: 'New York Red Bulls', years: '2015–2019' }, { club: 'RB Leipzig', years: '2019–2022' }, { club: 'Leeds', years: '2022–2023' }, { club: 'Bournemouth', years: '2023–' }] },
  { name:'Dusan Vlahovic',     country:'Serbia',     countryCode:'SRB', position:'Forward',    club:'Juventus',         age:25, foot:'Left',  flag:'🇷🇸', caps:34,  goals:18,  totGoals:155,  marketValue:60,  clubs: [{ club: 'Partizan', years: '2016–2018' }, { club: 'Fiorentina', years: '2018–2022' }, { club: 'Juventus', years: '2022–' }] },
  { name:'Denzel Dumfries',    country:'Netherlands',countryCode:'NED', position:'Defender',   club:'Inter Milan',      age:28, foot:'Right', flag:'🇳🇱', caps:58,  goals:7,   totGoals:38,   marketValue:28,  clubs: [{ club: 'Sparta Rotterdam', years: '2015–2017' }, { club: 'Heerenveen', years: '2017–2018' }, { club: 'PSV', years: '2018–2021' }, { club: 'Inter Milan', years: '2021–' }] },
  { name:'Jeremie Frimpong',   country:'Netherlands',countryCode:'NED', position:'Defender',   club:'Bayer Leverkusen', age:24, foot:'Right', flag:'🇳🇱', caps:14,  goals:2,   totGoals:35,   marketValue:55,  clubs: [{ club: 'Celtic', years: '2019–2021' }, { club: 'Bayer Leverkusen', years: '2021–' }] },
  { name:'Nathan Ake',         country:'Netherlands',countryCode:'NED', position:'Defender',   club:'Man City',         age:30, foot:'Left',  flag:'🇳🇱', caps:50,  goals:5,   totGoals:22,   marketValue:35,  clubs: [{ club: 'Chelsea', years: '2012–2017' }, { club: 'Bournemouth', years: '2017–2020' }, { club: 'Man City', years: '2020–' }] },
  { name:'Christian Eriksen',  country:'Denmark',    countryCode:'DEN', position:'Midfielder', club:'Man United',       age:34, foot:'Right', flag:'🇩🇰', caps:138, goals:44,  totGoals:165,  marketValue:6,   clubs: [{ club: 'Ajax', years: '2010–2013' }, { club: 'Tottenham', years: '2013–2020' }, { club: 'Inter Milan', years: '2020–2021' }, { club: 'Brentford', years: '2022' }, { club: 'Man United', years: '2022–' }] },
  { name:'Rasmus Hojlund',     country:'Denmark',    countryCode:'DEN', position:'Forward',    club:'Man United',       age:22, foot:'Left',  flag:'🇩🇰', caps:22,  goals:10,  totGoals:75,   marketValue:60,  clubs: [{ club: 'Copenhagen', years: '2020–2022' }, { club: 'Sturm Graz', years: '2022' }, { club: 'Atalanta', years: '2022–2023' }, { club: 'Man United', years: '2023–' }] },
  { name:'Alexis Sanchez',     country:'Chile',      countryCode:'CHI', position:'Forward',    club:'Udinese',          age:36, foot:'Right', flag:'🇨🇱', caps:162, goals:51,  totGoals:295,  marketValue:2,   clubs: [{ club: 'Cobreloa', years: '2005–2006' }, { club: 'Udinese', years: '2006–2011' }, { club: 'Colo-Colo (loan)', years: '2006–2007' }, { club: 'River Plate (loan)', years: '2007–2008' }, { club: 'Barcelona', years: '2011–2014' }, { club: 'Arsenal', years: '2014–2018' }, { club: 'Man United', years: '2018–2020' }, { club: 'Inter Milan', years: '2019–2022' }, { club: 'Marseille', years: '2022–2023' }, { club: 'Inter Milan', years: '2023–2024' }, { club: 'Udinese', years: '2024–' }] },
  { name:'Federico Chiesa',    country:'Italy',      countryCode:'ITA', position:'Forward',    club:'Liverpool',        age:27, foot:'Right', flag:'🇮🇹', caps:55,  goals:9,   totGoals:95,   marketValue:30,  clubs: [{ club: 'Fiorentina', years: '2016–2020' }, { club: 'Juventus', years: '2020–2024' }, { club: 'Liverpool', years: '2024–' }] },

// ─── 50 NEW PLAYERS (all at 2026 World Cup) ───────────────────────────────────

// SWEDEN
,{ name:'Viktor Gyokeres',     country:'Sweden',     countryCode:'SWE', position:'Forward',    club:'Arsenal',          age:28, foot:'Right', flag:'🇸🇪', caps:32,  goals:19,  totGoals:220,  marketValue:100, clubs: [{ club: 'Brighton', years: '2021–2022' }, { club: 'Coventry City', years: '2022–2023' }, { club: 'Sporting CP', years: '2023–2025' }, { club: 'Arsenal', years: '2025–' }] }
,{ name:'Alexander Isak',      country:'Sweden',     countryCode:'SWE', position:'Forward',    club:'Liverpool',        age:26, foot:'Right', flag:'🇸🇪', caps:38,  goals:14,  totGoals:145,  marketValue:90,  clubs: [{ club: 'AIK', years: '2016–2017' }, { club: 'Borussia Dortmund', years: '2017–2019' }, { club: 'Willem II (loan)', years: '2018–2019' }, { club: 'Real Sociedad', years: '2019–2022' }, { club: 'Newcastle', years: '2022–2025' }, { club: 'Liverpool', years: '2025–' }] }

// NORWAY
,{ name:'Martin Odegaard',     country:'Norway',     countryCode:'NOR', position:'Midfielder', club:'Arsenal',          age:27, foot:'Left',  flag:'🇳🇴', caps:78,  goals:18,  totGoals:82,   marketValue:80,  clubs: [{ club: 'Stromsgodset', years: '2014' }, { club: 'Real Madrid', years: '2015–2021' }, { club: 'Heerenveen (loan)', years: '2016–2017' }, { club: 'Vitesse (loan)', years: '2017–2018' }, { club: 'Real Sociedad (loan)', years: '2019–2021' }, { club: 'Arsenal (loan)', years: '2021' }, { club: 'Arsenal', years: '2021–' }] }
,{ name:'Alexander Sorloth',   country:'Norway',     countryCode:'NOR', position:'Forward',    club:'Atletico Madrid',  age:30, foot:'Right', flag:'🇳🇴', caps:55,  goals:24,  totGoals:140,  marketValue:35,  clubs: [{ club: 'Rosenborg', years: '2014–2018' }, { club: 'Crystal Palace', years: '2018–2019' }, { club: 'Gent (loan)', years: '2019' }, { club: 'Trabzonspor (loan)', years: '2019–2020' }, { club: 'RB Leipzig', years: '2020–2022' }, { club: 'Real Sociedad', years: '2022–2024' }, { club: 'Atletico Madrid', years: '2024–' }] }

// BRAZIL
,{ name:'Neymar',              country:'Brazil',     countryCode:'BRA', position:'Forward',    club:'Santos',           age:34, foot:'Right', flag:'🇧🇷', caps:128, goals:79,  totGoals:460,  marketValue:8,   clubs: [{ club: 'Santos', years: '2009–2013' }, { club: 'Barcelona', years: '2013–2017' }, { club: 'PSG', years: '2017–2023' }, { club: 'Al Hilal', years: '2023–2024' }, { club: 'Santos', years: '2025–' }] }
,{ name:'Bruno Guimaraes',     country:'Brazil',     countryCode:'BRA', position:'Midfielder', club:'Newcastle',        age:27, foot:'Right', flag:'🇧🇷', caps:38,  goals:6,   totGoals:42,   marketValue:80,  clubs: [{ club: 'Athletico Paranaense', years: '2018–2020' }, { club: 'Lyon', years: '2020–2022' }, { club: 'Newcastle', years: '2022–' }] }
,{ name:'Endrick',             country:'Brazil',     countryCode:'BRA', position:'Forward',    club:'Lyon',             age:19, foot:'Left',  flag:'🇧🇷', caps:18,  goals:7,   totGoals:52,   marketValue:60,  clubs: [{ club: 'Palmeiras', years: '2022–2024' }, { club: 'Real Madrid', years: '2024–2025' }, { club: 'Lyon (loan)', years: '2025–' }] }
,{ name:'Gabriel Martinelli',  country:'Brazil',     countryCode:'BRA', position:'Forward',    club:'Arsenal',          age:23, foot:'Right', flag:'🇧🇷', caps:25,  goals:6,   totGoals:90,   marketValue:60,  clubs: [{ club: 'Ituano', years: '2019' }, { club: 'Arsenal', years: '2019–' }] }
,{ name:'Lucas Paqueta',       country:'Brazil',     countryCode:'BRA', position:'Midfielder', club:'Flamengo',         age:28, foot:'Right', flag:'🇧🇷', caps:58,  goals:9,   totGoals:85,   marketValue:40,  clubs: [{ club: 'Flamengo', years: '2016–2019' }, { club: 'AC Milan', years: '2019–2020' }, { club: 'Lyon', years: '2020–2022' }, { club: 'West Ham', years: '2022–2025' }, { club: 'Flamengo', years: '2025–' }] }

// FRANCE
,{ name:'Bradley Barcola',     country:'France',     countryCode:'FRA', position:'Forward',    club:'PSG',              age:22, foot:'Left',  flag:'🇫🇷', caps:18,  goals:5,   totGoals:60,   marketValue:80,  clubs: [{ club: 'Lyon', years: '2021–2023' }, { club: 'PSG', years: '2023–' }] }
,{ name:'Eduardo Camavinga',   country:'France',     countryCode:'FRA', position:'Midfielder', club:'Real Madrid',      age:22, foot:'Left',  flag:'🇫🇷', caps:22,  goals:2,   totGoals:20,   marketValue:90,  clubs: [{ club: 'Rennes', years: '2019–2021' }, { club: 'Real Madrid', years: '2021–' }] }
,{ name:'Warren Zaire-Emery',  country:'France',     countryCode:'FRA', position:'Midfielder', club:'PSG',              age:20, foot:'Right', flag:'🇫🇷', caps:12,  goals:2,   totGoals:18,   marketValue:70,  clubs: [{ club: 'PSG', years: '2022–' }] }
,{ name:'Michael Olise',       country:'France',     countryCode:'FRA', position:'Forward',    club:'Bayern Munich',    age:23, foot:'Right', flag:'🇫🇷', caps:14,  goals:4,   totGoals:70,   marketValue:80,  clubs: [{ club: 'Reading', years: '2019–2021' }, { club: 'Crystal Palace', years: '2021–2024' }, { club: 'Bayern Munich', years: '2024–' }] }

// SPAIN
,{ name:'Martin Zubimendi',    country:'Spain',      countryCode:'ESP', position:'Midfielder', club:'Arsenal',          age:25, foot:'Right', flag:'🇪🇸', caps:20,  goals:1,   totGoals:8,    marketValue:70,  clubs: [{ club: 'Real Sociedad', years: '2019–2025' }, { club: 'Arsenal', years: '2025–' }] }
,{ name:'Mikel Oyarzabal',     country:'Spain',      countryCode:'ESP', position:'Forward',    club:'Real Sociedad',    age:29, foot:'Left',  flag:'🇪🇸', caps:62,  goals:23,  totGoals:130,  marketValue:45,  clubs: [{ club: 'Real Sociedad', years: '2015–' }] }
,{ name:'Fabian Ruiz',         country:'Spain',      countryCode:'ESP', position:'Midfielder', club:'PSG',              age:29, foot:'Left',  flag:'🇪🇸', caps:42,  goals:8,   totGoals:68,   marketValue:50,  clubs: [{ club: 'Real Betis', years: '2016–2018' }, { club: 'Napoli', years: '2018–2022' }, { club: 'PSG', years: '2022–' }] }

// GERMANY
,{ name:'Leroy Sane',          country:'Germany',    countryCode:'GER', position:'Forward',    club:'Bayern Munich',    age:30, foot:'Right', flag:'🇩🇪', caps:64,  goals:14,  totGoals:155,  marketValue:40,  clubs: [{ club: 'Schalke 04', years: '2014–2016' }, { club: 'Man City', years: '2016–2020' }, { club: 'Bayern Munich', years: '2020–' }] }
,{ name:'Toni Kroos',          country:'Germany',    countryCode:'GER', position:'Midfielder', club:'Real Madrid',      age:35, foot:'Right', flag:'🇩🇪', caps:108, goals:17,  totGoals:78,   marketValue:10,  clubs: [{ club: 'Bayern Munich', years: '2007–2014' }, { club: 'Bayer Leverkusen (loan)', years: '2009–2010' }, { club: 'Real Madrid', years: '2014–' }] }
,{ name:'Nico Schlotterbeck',  country:'Germany',    countryCode:'GER', position:'Defender',   club:'Borussia Dortmund',age:25, foot:'Left',  flag:'🇩🇪', caps:24,  goals:2,   totGoals:15,   marketValue:45,  clubs: [{ club: 'SC Freiburg', years: '2019–2022' }, { club: 'Borussia Dortmund', years: '2022–' }] }

// ARGENTINA
,{ name:'Alejandro Garnacho',  country:'Argentina',  countryCode:'ARG', position:'Forward',    club:'Man United',       age:21, foot:'Left',  flag:'🇦🇷', caps:18,  goals:5,   totGoals:40,   marketValue:65,  clubs: [{ club: 'Atletico Madrid', years: '2021–2022' }, { club: 'Man United', years: '2022–' }] }

// PORTUGAL
,{ name:'Joao Neves',          country:'Portugal',   countryCode:'POR', position:'Midfielder', club:'PSG',              age:20, foot:'Right', flag:'🇵🇹', caps:16,  goals:1,   totGoals:10,   marketValue:80,  clubs: [{ club: 'Benfica', years: '2022–2024' }, { club: 'PSG', years: '2024–' }] }
,{ name:'Vitinha',             country:'Portugal',   countryCode:'POR', position:'Midfielder', club:'PSG',              age:25, foot:'Right', flag:'🇵🇹', caps:38,  goals:4,   totGoals:35,   marketValue:90,  clubs: [{ club: 'Porto', years: '2018–2022' }, { club: 'Wolverhampton (loan)', years: '2021–2022' }, { club: 'PSG', years: '2022–' }] }
,{ name:'Diogo Jota',          country:'Portugal',   countryCode:'POR', position:'Forward',    club:'Liverpool',        age:28, foot:'Right', flag:'🇵🇹', caps:54,  goals:21,  totGoals:135,  marketValue:55,  clubs: [{ club: 'Pacos Ferreira', years: '2014–2017' }, { club: 'Atletico Madrid', years: '2017–2018' }, { club: 'Wolves', years: '2018–2020' }, { club: 'Liverpool', years: '2020–' }] }

// ENGLAND
,{ name:'Cole Palmer',         country:'England',    countryCode:'ENG', position:'Midfielder', club:'Chelsea',          age:23, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:22,  goals:7,   totGoals:85,   marketValue:100, clubs: [{ club: 'Man City', years: '2020–2023' }, { club: 'Chelsea', years: '2023–' }] }
,{ name:'Kobbie Mainoo',       country:'England',    countryCode:'ENG', position:'Midfielder', club:'Man United',       age:20, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:14,  goals:2,   totGoals:12,   marketValue:65,  clubs: [{ club: 'Man United', years: '2023–' }] }
,{ name:'Trent Alexander-Arnold',country:'England', countryCode:'ENG', position:'Defender',   club:'Real Madrid',      age:27, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:35,  goals:3,   totGoals:28,   marketValue:70,  clubs: [{ club: 'Liverpool', years: '2016–2025' }, { club: 'Real Madrid', years: '2025–' }] }
,{ name:'Eberechi Eze',        country:'England',    countryCode:'ENG', position:'Midfielder', club:'Crystal Palace',   age:26, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', caps:16,  goals:4,   totGoals:72,   marketValue:55,  clubs: [{ club: 'QPR', years: '2019–2021' }, { club: 'Crystal Palace', years: '2021–' }] }

// USA
,{ name:'Gio Reyna',           country:'USA',        countryCode:'USA', position:'Midfielder', club:'Borussia Monchengladbach', age:23, foot:'Right', flag:'🇺🇸', caps:38,  goals:9,   totGoals:28,   marketValue:18,  clubs: [{ club: 'Borussia Dortmund', years: '2020–2024' }, { club: 'Nottingham Forest (loan)', years: '2023–2024' }, { club: 'Borussia Monchengladbach', years: '2024–' }] }
,{ name:'Ricardo Pepi',        country:'USA',        countryCode:'USA', position:'Forward',    club:'PSV',              age:22, foot:'Right', flag:'🇺🇸', caps:30,  goals:12,  totGoals:65,   marketValue:20,  clubs: [{ club: 'FC Dallas', years: '2020–2022' }, { club: 'Augsburg', years: '2022–2023' }, { club: 'PSV', years: '2022–2025' }, { club: 'PSV', years: '2025–' }] }

// ITALY
,{ name:'Sandro Tonali',       country:'Italy',      countryCode:'ITA', position:'Midfielder', club:'Newcastle',        age:25, foot:'Right', flag:'🇮🇹', caps:35,  goals:4,   totGoals:32,   marketValue:55,  clubs: [{ club: 'Brescia', years: '2017–2021' }, { club: 'AC Milan', years: '2021–2023' }, { club: 'Newcastle', years: '2023–' }] }
,{ name:'Gianluigi Donnarumma',country:'Italy',      countryCode:'ITA', position:'Goalkeeper', club:'PSG',              age:26, foot:'Right', flag:'🇮🇹', caps:60,  goals:0,   totGoals:0,    marketValue:45,  clubs: [{ club: 'AC Milan', years: '2015–2021' }, { club: 'PSG', years: '2021–' }] }
,{ name:'Giacomo Raspadori',   country:'Italy',      countryCode:'ITA', position:'Forward',    club:'Napoli',           age:25, foot:'Right', flag:'🇮🇹', caps:40,  goals:10,  totGoals:60,   marketValue:38,  clubs: [{ club: 'Sassuolo', years: '2018–2022' }, { club: 'Napoli', years: '2022–' }] }
,{ name:'Nicolo Barella',      country:'Italy',      countryCode:'ITA', position:'Midfielder', club:'Inter Milan',      age:27, foot:'Right', flag:'🇮🇹', caps:65,  goals:8,   totGoals:42,   marketValue:70,  clubs: [{ club: 'Cagliari', years: '2015–2019' }, { club: 'Inter Milan', years: '2019–' }] }

// BELGIUM
,{ name:'Amadou Onana',        country:'Belgium',    countryCode:'BEL', position:'Midfielder', club:'Aston Villa',      age:23, foot:'Right', flag:'🇧🇪', caps:28,  goals:2,   totGoals:15,   marketValue:55,  clubs: [{ club: 'Lille', years: '2021–2022' }, { club: 'Everton', years: '2022–2024' }, { club: 'Aston Villa', years: '2024–' }] }
,{ name:'Lois Openda',         country:'Belgium',    countryCode:'BEL', position:'Forward',    club:'RB Leipzig',       age:24, foot:'Right', flag:'🇧🇪', caps:24,  goals:8,   totGoals:98,   marketValue:65,  clubs: [{ club: 'Club Brugge', years: '2019–2022' }, { club: 'Lens', years: '2022–2023' }, { club: 'RB Leipzig', years: '2023–' }] }

// NETHERLANDS
,{ name:'Tijjani Reijnders',   country:'Netherlands',countryCode:'NED', position:'Midfielder', club:'AC Milan',         age:26, foot:'Right', flag:'🇳🇱', caps:25,  goals:5,   totGoals:35,   marketValue:55,  clubs: [{ club: 'AZ Alkmaar', years: '2019–2023' }, { club: 'AC Milan', years: '2023–' }] }

// CROATIA
,{ name:'Andrej Kramaric',     country:'Croatia',    countryCode:'CRO', position:'Forward',    club:'Hoffenheim',       age:33, foot:'Right', flag:'🇭🇷', caps:90,  goals:36,  totGoals:200,  marketValue:8,   clubs: [{ club: 'Rijeka', years: '2009–2014' }, { club: 'Leicester City', years: '2015' }, { club: 'Hoffenheim', years: '2015–' }] }
,{ name:'Mario Pasalic',       country:'Croatia',    countryCode:'CRO', position:'Midfielder', club:'Atalanta',         age:29, foot:'Right', flag:'🇭🇷', caps:58,  goals:12,  totGoals:65,   marketValue:22,  clubs: [{ club: 'Hajduk Split', years: '2013–2014' }, { club: 'Chelsea', years: '2014–2022' }, { club: 'Atalanta', years: '2022–' }] }

// MEXICO
,{ name:'Raul Jimenez',        country:'Mexico',     countryCode:'MEX', position:'Forward',    club:'Fulham',           age:34, foot:'Right', flag:'🇲🇽', caps:112, goals:42,  totGoals:220,  marketValue:8,   clubs: [{ club: 'Club America', years: '2011–2014' }, { club: 'Atletico Madrid', years: '2014–2015' }, { club: 'Benfica', years: '2015–2019' }, { club: 'Wolves', years: '2019–2023' }, { club: 'Fulham', years: '2023–' }] }

// SENEGAL
,{ name:'Ismaila Sarr',        country:'Senegal',    countryCode:'SEN', position:'Forward',    club:'Marseille',        age:26, foot:'Right', flag:'🇸🇳', caps:55,  goals:14,  totGoals:92,   marketValue:28,  clubs: [{ club: 'Metz', years: '2015–2016' }, { club: 'Rennes', years: '2016–2019' }, { club: 'Watford', years: '2019–2023' }, { club: 'Crystal Palace', years: '2023–2024' }, { club: 'Marseille', years: '2024–' }] }
,{ name:'Pape Gueye',          country:'Senegal',    countryCode:'SEN', position:'Midfielder', club:'Marseille',        age:25, foot:'Right', flag:'🇸🇳', caps:22,  goals:2,   totGoals:12,   marketValue:18,  clubs: [{ club: 'Le Havre', years: '2017–2020' }, { club: 'Marseille', years: '2020–' }] }

// SOUTH KOREA
,{ name:'Lee Kang-in',         country:'South Korea',countryCode:'KOR', position:'Midfielder', club:'PSG',              age:23, foot:'Right', flag:'🇰🇷', caps:38,  goals:9,   totGoals:52,   marketValue:45,  clubs: [{ club: 'Valencia', years: '2019–2023' }, { club: 'Mallorca (loan)', years: '2022–2023' }, { club: 'PSG', years: '2023–' }] }
,{ name:'Hwang Hee-chan',       country:'South Korea',countryCode:'KOR', position:'Forward',    club:'Wolves',           age:28, foot:'Right', flag:'🇰🇷', caps:62,  goals:16,  totGoals:85,   marketValue:20,  clubs: [{ club: 'Red Bull Salzburg', years: '2015–2020' }, { club: 'Hamburg (loan)', years: '2019–2020' }, { club: 'RB Leipzig', years: '2020–2021' }, { club: 'Wolves', years: '2021–' }] }

// CANADA
,{ name:'Cyle Larin',          country:'Canada',     countryCode:'CAN', position:'Forward',    club:'Club Brugge',      age:30, foot:'Right', flag:'🇨🇦', caps:65,  goals:28,  totGoals:145,  marketValue:8,   clubs: [{ club: 'Orlando City', years: '2015–2018' }, { club: 'Besiktas', years: '2018–2021' }, { club: 'Club Brugge', years: '2021–2024' }, { club: 'Mallorca', years: '2024–2025' }, { club: 'Club Brugge', years: '2025–' }] }

// SWITZERLAND
,{ name:'Gregor Kobel',        country:'Switzerland',countryCode:'CHE', position:'Goalkeeper', club:'Borussia Dortmund',age:27, foot:'Right', flag:'🇨🇭', caps:28,  goals:0,   totGoals:0,    marketValue:35,  clubs: [{ club: 'Stuttgart', years: '2017–2021' }, { club: 'Borussia Dortmund', years: '2021–' }] }
,{ name:'Manuel Akanji',       country:'Switzerland',countryCode:'CHE', position:'Defender',   club:'Inter Milan',      age:29, foot:'Right', flag:'🇨🇭', caps:55,  goals:2,   totGoals:10,   marketValue:40,  clubs: [{ club: 'Basel', years: '2015–2018' }, { club: 'Borussia Dortmund', years: '2018–2022' }, { club: 'Man City', years: '2022–2025' }, { club: 'Inter Milan', years: '2025–' }] }
,{ name:'Breel Embolo',        country:'Switzerland',countryCode:'CHE', position:'Forward',    club:'Monaco',           age:27, foot:'Right', flag:'🇨🇭', caps:62,  goals:16,  totGoals:115,  marketValue:20,  clubs: [{ club: 'Basel', years: '2014–2016' }, { club: 'Schalke 04', years: '2016–2019' }, { club: 'Borussia Monchengladbach', years: '2019–2022' }, { club: 'Monaco', years: '2022–' }] }

// AUSTRIA
,{ name:'Marcel Sabitzer',     country:'Austria',    countryCode:'AUT', position:'Midfielder', club:'Borussia Dortmund',age:31, foot:'Right', flag:'🇦🇹', caps:70,  goals:14,  totGoals:90,   marketValue:18,  clubs: [{ club: 'Red Bull Salzburg', years: '2012–2014' }, { club: 'RB Leipzig', years: '2014–2021' }, { club: 'Bayern Munich', years: '2021–2023' }, { club: 'Man United (loan)', years: '2023' }, { club: 'Borussia Dortmund', years: '2023–' }] }

// ECUADOR
,{ name:'Moises Caicedo',      country:'Ecuador',    countryCode:'ECU', position:'Midfielder', club:'Chelsea',          age:23, foot:'Right', flag:'🇪🇨', caps:45,  goals:3,   totGoals:18,   marketValue:90,  clubs: [{ club: 'Independiente del Valle', years: '2019–2021' }, { club: 'Brighton', years: '2021–2023' }, { club: 'Chelsea', years: '2023–' }] }

// URUGUAY
,{ name:'Ronald Araujo',       country:'Uruguay',    countryCode:'URU', position:'Defender',   club:'Barcelona',        age:25, foot:'Right', flag:'🇺🇾', caps:45,  goals:4,   totGoals:18,   marketValue:55,  clubs: [{ club: 'Boston River', years: '2016–2018' }, { club: 'Barcelona', years: '2020–' }] }

// JAPAN
,{ name:'Wataru Endo',         country:'Japan',      countryCode:'JPN', position:'Midfielder', club:'Liverpool',        age:31, foot:'Right', flag:'🇯🇵', caps:62,  goals:4,   totGoals:32,   marketValue:18,  clubs: [{ club: 'Urawa Red Diamonds', years: '2012–2017' }, { club: 'Sint-Truiden', years: '2017–2019' }, { club: 'Stuttgart', years: '2019–2023' }, { club: 'Liverpool', years: '2023–' }] }
,{ name:'Kaoru Mitoma',        country:'Japan',      countryCode:'JPN', position:'Forward',    club:'Brighton',         age:27, foot:'Left',  flag:'🇯🇵', caps:40,  goals:10,  totGoals:65,   marketValue:40,  clubs: [{ club: 'Kawasaki Frontale', years: '2019–2021' }, { club: 'Brighton', years: '2022–' }] }

// TURKEY
,{ name:'Arda Guler',          country:'Turkey',     countryCode:'TUR', position:'Midfielder', club:'Real Madrid',      age:20, foot:'Right', flag:'🇹🇷', caps:18,  goals:5,   totGoals:32,   marketValue:70,  clubs: [{ club: 'Fenerbahce', years: '2021–2023' }, { club: 'Real Madrid', years: '2023–' }] }

// COLOMBIA
,{ name:'Jhon Duran',          country:'Colombia',   countryCode:'COL', position:'Forward',    club:'Al-Nassr',         age:21, foot:'Right', flag:'🇨🇴', caps:12,  goals:4,   totGoals:48,   marketValue:40,  clubs: [{ club: 'Envigado', years: '2021–2022' }, { club: 'Chicago Fire', years: '2022–2023' }, { club: 'Aston Villa', years: '2023–2025' }, { club: 'Al-Nassr', years: '2025–' }] }
];