// src/lib/players.js
export const PLAYERS = [
  { name:'Lionel Messi',      country:'Argentina', countryCode:'ARG', position:'Forward',    club:'Inter Miami',      age:36, foot:'Left',  flag:'🇦🇷' },
  { name:'Lautaro Martinez',  country:'Argentina', countryCode:'ARG', position:'Forward',    club:'Inter Milan',      age:26, foot:'Right', flag:'🇦🇷' },
  { name:'Emiliano Martinez', country:'Argentina', countryCode:'ARG', position:'Goalkeeper', club:'Aston Villa',      age:31, foot:'Right', flag:'🇦🇷' },
  { name:'Kylian Mbappe',     country:'France',    countryCode:'FRA', position:'Forward',    club:'Real Madrid',      age:25, foot:'Right', flag:'🇫🇷' },
  { name:'Antoine Griezmann', country:'France',    countryCode:'FRA', position:'Forward',    club:'Atletico Madrid',  age:32, foot:'Left',  flag:'🇫🇷' },
  { name:'Aurelien Tchouameni',country:'France',   countryCode:'FRA', position:'Midfielder', club:'Real Madrid',      age:24, foot:'Right', flag:'🇫🇷' },
  { name:'Erling Haaland',    country:'Norway',    countryCode:'NOR', position:'Forward',    club:'Man City',         age:23, foot:'Left',  flag:'🇳🇴' },
  { name:'Vinicius Jr',       country:'Brazil',    countryCode:'BRA', position:'Forward',    club:'Real Madrid',      age:23, foot:'Right', flag:'🇧🇷' },
  { name:'Rodrygo',           country:'Brazil',    countryCode:'BRA', position:'Forward',    club:'Real Madrid',      age:23, foot:'Right', flag:'🇧🇷' },
  { name:'Alisson',           country:'Brazil',    countryCode:'BRA', position:'Goalkeeper', club:'Liverpool',        age:31, foot:'Right', flag:'🇧🇷' },
  { name:'Marquinhos',        country:'Brazil',    countryCode:'BRA', position:'Defender',   club:'PSG',              age:29, foot:'Right', flag:'🇧🇷' },
  { name:'Casemiro',          country:'Brazil',    countryCode:'BRA', position:'Midfielder', club:'Man United',       age:31, foot:'Right', flag:'🇧🇷' },
  { name:'Jude Bellingham',   country:'England',   countryCode:'ENG', position:'Midfielder', club:'Real Madrid',      age:20, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name:'Harry Kane',        country:'England',   countryCode:'ENG', position:'Forward',    club:'Bayern Munich',    age:30, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name:'Bukayo Saka',       country:'England',   countryCode:'ENG', position:'Forward',    club:'Arsenal',          age:22, foot:'Left',  flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name:'Phil Foden',        country:'England',   countryCode:'ENG', position:'Midfielder', club:'Man City',         age:23, foot:'Left',  flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name:'Declan Rice',       country:'England',   countryCode:'ENG', position:'Midfielder', club:'Arsenal',          age:25, foot:'Right', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name:'Robert Lewandowski',country:'Poland',    countryCode:'POL', position:'Forward',    club:'Barcelona',        age:35, foot:'Right', flag:'🇵🇱' },
  { name:'Pedri',             country:'Spain',     countryCode:'ESP', position:'Midfielder', club:'Barcelona',        age:21, foot:'Right', flag:'🇪🇸' },
  { name:'Gavi',              country:'Spain',     countryCode:'ESP', position:'Midfielder', club:'Barcelona',        age:19, foot:'Left',  flag:'🇪🇸' },
  { name:'Lamine Yamal',      country:'Spain',     countryCode:'ESP', position:'Forward',    club:'Barcelona',        age:16, foot:'Right', flag:'🇪🇸' },
  { name:'Alvaro Morata',     country:'Spain',     countryCode:'ESP', position:'Forward',    club:'AC Milan',         age:31, foot:'Right', flag:'🇪🇸' },
  { name:'Rodri',             country:'Spain',     countryCode:'ESP', position:'Midfielder', club:'Man City',         age:27, foot:'Right', flag:'🇪🇸' },
  { name:'Jamal Musiala',     country:'Germany',   countryCode:'GER', position:'Midfielder', club:'Bayern Munich',    age:21, foot:'Right', flag:'🇩🇪' },
  { name:'Florian Wirtz',     country:'Germany',   countryCode:'GER', position:'Midfielder', club:'Bayer Leverkusen', age:20, foot:'Left',  flag:'🇩🇪' },
  { name:'Manuel Neuer',      country:'Germany',   countryCode:'GER', position:'Goalkeeper', club:'Bayern Munich',    age:37, foot:'Right', flag:'🇩🇪' },
  { name:'Leroy Sane',        country:'Germany',   countryCode:'GER', position:'Forward',    club:'Bayern Munich',    age:27, foot:'Right', flag:'🇩🇪' },
  { name:'Joao Felix',        country:'Portugal',  countryCode:'POR', position:'Forward',    club:'Chelsea',          age:24, foot:'Right', flag:'🇵🇹' },
  { name:'Bruno Fernandes',   country:'Portugal',  countryCode:'POR', position:'Midfielder', club:'Man United',       age:29, foot:'Right', flag:'🇵🇹' },
  { name:'Ruben Dias',        country:'Portugal',  countryCode:'POR', position:'Defender',   club:'Man City',         age:26, foot:'Right', flag:'🇵🇹' },
  { name:'Cristiano Ronaldo', country:'Portugal',  countryCode:'POR', position:'Forward',    club:'Al Nassr',         age:39, foot:'Right', flag:'🇵🇹' },
  { name:'Raphinha',          country:'Brazil',    countryCode:'BRA', position:'Forward',    club:'Barcelona',        age:27, foot:'Left',  flag:'🇧🇷' },
  { name:'Achraf Hakimi',     country:'Morocco',   countryCode:'MAR', position:'Defender',   club:'PSG',              age:25, foot:'Right', flag:'🇲🇦' },
  { name:'Hakim Ziyech',      country:'Morocco',   countryCode:'MAR', position:'Midfielder', club:'Galatasaray',      age:30, foot:'Left',  flag:'🇲🇦' },
  { name:'Yassine Bounou',    country:'Morocco',   countryCode:'MAR', position:'Goalkeeper', club:'Al Hilal',         age:32, foot:'Right', flag:'🇲🇦' },
  { name:'Victor Osimhen',    country:'Nigeria',   countryCode:'NGA', position:'Forward',    club:'Galatasaray',      age:25, foot:'Right', flag:'🇳🇬' },
  { name:'Sadio Mane',        country:'Senegal',   countryCode:'SEN', position:'Forward',    club:'Al Nassr',         age:32, foot:'Right', flag:'🇸🇳' },
  { name:'Mohamed Salah',     country:'Egypt',     countryCode:'EGY', position:'Forward',    club:'Liverpool',        age:31, foot:'Left',  flag:'🇪🇬' },
  { name:'Son Heung-min',     country:'South Korea',countryCode:'KOR',position:'Forward',    club:'Tottenham',        age:31, foot:'Left',  flag:'🇰🇷' },
  { name:'Takumi Minamino',   country:'Japan',     countryCode:'JPN', position:'Midfielder', club:'Monaco',           age:29, foot:'Right', flag:'🇯🇵' },
  { name:'Ritsu Doan',        country:'Japan',     countryCode:'JPN', position:'Forward',    club:'Freiburg',         age:25, foot:'Right', flag:'🇯🇵' },
  { name:'Ivan Perisic',      country:'Croatia',   countryCode:'CRO', position:'Midfielder', club:'Hajduk Split',     age:34, foot:'Left',  flag:'🇭🇷' },
  { name:'Luka Modric',       country:'Croatia',   countryCode:'CRO', position:'Midfielder', club:'Real Madrid',      age:38, foot:'Right', flag:'🇭🇷' },
  { name:'Dominik Livakovic', country:'Croatia',   countryCode:'CRO', position:'Goalkeeper', club:'Fenerbahce',       age:28, foot:'Right', flag:'🇭🇷' },
  { name:'Memphis Depay',     country:'Netherlands',countryCode:'NED',position:'Forward',    club:'Atletico Madrid',  age:29, foot:'Right', flag:'🇳🇱' },
  { name:'Virgil van Dijk',   country:'Netherlands',countryCode:'NED',position:'Defender',   club:'Liverpool',        age:32, foot:'Right', flag:'🇳🇱' },
  { name:'Cody Gakpo',        country:'Netherlands',countryCode:'NED',position:'Forward',    club:'Liverpool',        age:24, foot:'Right', flag:'🇳🇱' },
  { name:'Frenkie de Jong',   country:'Netherlands',countryCode:'NED',position:'Midfielder', club:'Barcelona',        age:26, foot:'Right', flag:'🇳🇱' },
  { name:'Christian Pulisic', country:'USA',       countryCode:'USA', position:'Forward',    club:'AC Milan',         age:25, foot:'Right', flag:'🇺🇸' },
  { name:'Alphonso Davies',   country:'Canada',    countryCode:'CAN', position:'Defender',   club:'Bayern Munich',    age:23, foot:'Left',  flag:'🇨🇦' },
  { name:'Jonathan David',    country:'Canada',    countryCode:'CAN', position:'Forward',    club:'Lille',            age:24, foot:'Right', flag:'🇨🇦' },
  { name:'Hirving Lozano',    country:'Mexico',    countryCode:'MEX', position:'Forward',    club:'PSV',              age:28, foot:'Right', flag:'🇲🇽' },
  { name:'Edson Alvarez',     country:'Mexico',    countryCode:'MEX', position:'Midfielder', club:'West Ham',         age:26, foot:'Right', flag:'🇲🇽' },
  { name:'Paulo Dybala',      country:'Argentina', countryCode:'ARG', position:'Forward',    club:'Roma',             age:30, foot:'Left',  flag:'🇦🇷' },
  { name:'Julian Alvarez',    country:'Argentina', countryCode:'ARG', position:'Forward',    club:'Atletico Madrid',  age:24, foot:'Right', flag:'🇦🇷' },
  { name:'Darwin Nunez',      country:'Uruguay',   countryCode:'URU', position:'Forward',    club:'Liverpool',        age:24, foot:'Right', flag:'🇺🇾' },
  { name:'Federico Valverde', country:'Uruguay',   countryCode:'URU', position:'Midfielder', club:'Real Madrid',      age:25, foot:'Right', flag:'🇺🇾' },
  { name:'Luis Diaz',         country:'Colombia',  countryCode:'COL', position:'Forward',    club:'Liverpool',        age:27, foot:'Right', flag:'🇨🇴' },
  { name:'James Rodriguez',   country:'Colombia',  countryCode:'COL', position:'Midfielder', club:'Rayo Vallecano',   age:32, foot:'Right', flag:'🇨🇴' },
  { name:'Alexis Mac Allister',country:'Argentina',countryCode:'ARG', position:'Midfielder', club:'Liverpool',        age:25, foot:'Right', flag:'🇦🇷' },
  { name:'Granit Xhaka',      country:'Switzerland',countryCode:'CHE',position:'Midfielder', club:'Bayer Leverkusen', age:31, foot:'Left',  flag:'🇨🇭' },
  { name:'Xherdan Shaqiri',   country:'Switzerland',countryCode:'CHE',position:'Midfielder', club:'Chicago Fire',     age:32, foot:'Right', flag:'🇨🇭' },
  { name:'Romelu Lukaku',     country:'Belgium',   countryCode:'BEL', position:'Forward',    club:'Roma',             age:30, foot:'Right', flag:'🇧🇪' },
  { name:'Kevin De Bruyne',   country:'Belgium',   countryCode:'BEL', position:'Midfielder', club:'Man City',         age:32, foot:'Right', flag:'🇧🇪' },
  { name:'Thibaut Courtois',  country:'Belgium',   countryCode:'BEL', position:'Goalkeeper', club:'Real Madrid',      age:31, foot:'Right', flag:'🇧🇪' },
].map((p, idx) => ({ ...p, id: String(idx + 1) }));
