export const TRIVIA_QUESTIONS = [

  { id: 'h01', cat: 'history', q: 'Which nation has won the FIFA World Cup the most times?', opts: ['Germany', 'Italy', 'Brazil', 'Argentina'], ans: 2 },
  { id: 'h02', cat: 'history', q: 'In what year was the first FIFA World Cup held?', opts: ['1926', '1928', '1930', '1934'], ans: 2 },
  { id: 'h03', cat: 'history', q: 'Which club won the inaugural UEFA Champions League in 1956?', opts: ['Barcelona', 'Real Madrid', 'Juventus', 'AC Milan'], ans: 1 },
  { id: 'h04', cat: 'history', q: 'England won the World Cup only once — in which year?', opts: ['1962', '1966', '1970', '1974'], ans: 1 },
  { id: 'h05', cat: 'history', q: 'Which player scored the "Hand of God" goal at the 1986 World Cup?', opts: ['Pelé', 'Diego Maradona', 'Ronaldo', 'Zinedine Zidane'], ans: 1 },
  { id: 'h06', cat: 'history', q: 'Germany and which other nation played the longest-running World Cup final rivalry before 2022?', opts: ['Brazil', 'Argentina', 'Italy', 'Netherlands'], ans: 1 },
  { id: 'h07', cat: 'history', q: 'Which club became the first English side to win the European Cup in 1968?', opts: ['Liverpool', 'Tottenham', 'Manchester United', 'Arsenal'], ans: 2 },
  { id: 'h08', cat: 'history', q: 'At which World Cup did Zinedine Zidane head-butt Marco Materazzi in the final?', opts: ['1998', '2002', '2006', '2010'], ans: 2 },
  { id: 'h09', cat: 'history', q: "Who scored the winning penalty for Portugal in the 2016 Euro final — it wasn't Ronaldo (he was injured)?", opts: ['Nani', 'Éder', 'Quaresma', 'João Mário'], ans: 1 },
  { id: 'h10', cat: 'history', q: "Which nation hosted the first Women's FIFA World Cup in 1991?", opts: ['USA', 'Germany', 'China', 'Sweden'], ans: 2 },
  { id: 'h11', cat: 'history', q: 'What was the score in the infamous "Disgrace of Gijón" World Cup match in 1982?', opts: ['1-0', '2-0', '3-0', '1-1'], ans: 0 },
  { id: 'h12', cat: 'history', q: 'Who is the all-time top scorer in FIFA World Cup history?', opts: ['Ronaldo (Brazil)', 'Miroslav Klose', 'Gerd Müller', 'Just Fontaine'], ans: 1 },
  { id: 'h13', cat: 'history', q: 'Which club won five consecutive European Cups from 1956 to 1960?', opts: ['AC Milan', 'Benfica', 'Real Madrid', 'Internazionale'], ans: 2 },
  { id: 'h14', cat: 'history', q: "Leicester City's miraculous Premier League title was won in which season?", opts: ['2014-15', '2015-16', '2016-17', '2013-14'], ans: 1 },
  { id: 'h15', cat: 'history', q: 'Which Brazilian scored a hat-trick at the 1970 World Cup final?', opts: ['Pelé', 'Rivelino', 'Jairzinho', 'Tostão'], ans: 0 },
  { id: 'h16', cat: 'history', q: 'Who scored the very first goal in FIFA World Cup history, at the 1930 tournament?', opts: ['Lucien Laurent', 'Guillermo Stábile', 'Bert Patenaude', 'Adalbert Deșu'], ans: 0 },
  { id: 'h17', cat: 'history', q: 'What is the "Maracanazo," the result that stunned host nation Brazil at the 1950 World Cup?', opts: ["Brazil lost the decisive final match to Uruguay, 2-1", 'Brazil were disqualified for fielding an ineligible player', "The Maracanã's stands collapsed mid-tournament", 'Brazil forfeited the final after a walkout'], ans: 0 },
  { id: 'h18', cat: 'history', q: 'Which goalkeeper remains the only one ever to win the Ballon d\'Or, back in 1963?', opts: ['Gianluigi Buffon', 'Lev Yashin', 'Iker Casillas', 'Manuel Neuer'], ans: 1 },
  { id: 'h19', cat: 'history', q: 'Italy captain and goalkeeper Dino Zoff became the oldest player to win a World Cup in 1982, at what age?', opts: ['38', '39', '40', '42'], ans: 2 },
  { id: 'h20', cat: 'history', q: 'At what age did Pelé become the youngest player to win a World Cup, with Brazil in 1958?', opts: ['16', '17', '18', '19'], ans: 1 },
  { id: 'h21', cat: 'history', q: 'Which country hosted the first-ever European Championship (then the European Nations\' Cup) in 1960?', opts: ['France', 'Spain', 'Italy', 'USSR'], ans: 0 },
  { id: 'h22', cat: 'history', q: 'Which nation did host West Germany defeat in the 1974 World Cup final?', opts: ['Netherlands', 'Poland', 'Brazil', 'Argentina'], ans: 0 },
  { id: 'h23', cat: 'history', q: 'Which nation won the very first Women\'s FIFA World Cup, held in China in 1991?', opts: ['United States', 'Norway', 'Germany', 'Sweden'], ans: 0 },
  { id: 'h24', cat: 'history', q: 'What unusual format decided the champion of the 1950 World Cup, rather than a single knockout final?', opts: ['A final round-robin group among four teams', 'A two-legged final', 'A penalty shootout playoff between group winners', 'A golden-goal decider'], ans: 0 },
  { id: 'h25', cat: 'history', q: 'In the same 1986 quarter-final in which he scored the "Hand of God," Maradona also scored the "Goal of the Century" — how many England outfield players did he dribble past before finishing?', opts: ['3', '4', '5', '6'], ans: 2 },

  { id: 't01', cat: 'transfer', q: 'What was the world-record transfer fee when Neymar moved from Barcelona to PSG in 2017?', opts: ['€150m', '€180m', '€200m', '€222m'], ans: 3 },
  { id: 't02', cat: 'transfer', q: 'Which club did Cristiano Ronaldo join when he left Real Madrid in 2018?', opts: ['PSG', 'Juventus', 'Manchester City', 'Inter Milan'], ans: 1 },
  { id: 't03', cat: 'transfer', q: 'From which club did Manchester United sign Bruno Fernandes in January 2020?', opts: ['Porto', 'Benfica', 'Sporting CP', 'Braga'], ans: 2 },
  { id: 't04', cat: 'transfer', q: 'In what year did Gareth Bale first move to Real Madrid from Tottenham?', opts: ['2012', '2013', '2014', '2015'], ans: 1 },
  { id: 't05', cat: 'transfer', q: 'Which club sold Jack Grealish to Manchester City for £100m in 2021?', opts: ['Nottingham Forest', 'Derby County', 'Aston Villa', 'Wolves'], ans: 2 },
  { id: 't06', cat: 'transfer', q: 'Enzo Fernández joined Chelsea for a British-record fee from which club?', opts: ['Ajax', 'River Plate', 'Benfica', 'Flamengo'], ans: 2 },
  { id: 't07', cat: 'transfer', q: 'Which club did Antoine Griezmann leave to join Barcelona in 2019?', opts: ['PSG', 'Lyon', 'Atletico Madrid', 'Monaco'], ans: 2 },
  { id: 't08', cat: 'transfer', q: 'Romelu Lukaku became the most expensive Belgian player ever when he joined which club for £97.5m in 2021?', opts: ['Manchester United', 'Inter Milan', 'Chelsea', 'PSG'], ans: 2 },
  { id: 't09', cat: 'transfer', q: 'For what reported fixed fee did Real Madrid sign Jude Bellingham from Borussia Dortmund?', opts: ['€80m', '€90m', '€103m', '€120m'], ans: 2 },
  { id: 't10', cat: 'transfer', q: 'Which club signed Karim Benzema after he left Real Madrid in 2023?', opts: ['PSG', 'Inter Miami', 'Al-Ittihad', 'Al-Nassr'], ans: 2 },
  { id: 't11', cat: 'transfer', q: 'Which South American club sold Vinicius Jr. to Real Madrid when he was just 16?', opts: ['Santos', 'Flamengo', 'Palmeiras', 'Cruzeiro'], ans: 1 },
  { id: 't12', cat: 'transfer', q: 'Zlatan Ibrahimović joined AC Milan permanently in 2020 from which club?', opts: ['LA Galaxy', 'PSG', 'Manchester United', 'Inter Milan'], ans: 2 },
  { id: 't13', cat: 'transfer', q: "As of 2026, whose 2017 transfer to PSG remains the outright world-record transfer fee ever paid for a player?", opts: ['Kylian Mbappé', 'Neymar', 'Cristiano Ronaldo', 'Ousmane Dembélé'], ans: 1 },
  { id: 't14', cat: 'transfer', q: 'Who is the most expensive goalkeeper in football history, moving to Chelsea for around €80m in 2018?', opts: ['Alisson Becker', 'Ederson', 'Kepa Arrizabalaga', 'Gianluigi Donnarumma'], ans: 2 },
  { id: 't15', cat: 'transfer', q: "Which player holds the world-record transfer fee for a defender, having joined Manchester City from RB Leipzig?", opts: ['Virgil van Dijk', 'Joško Gvardiol', 'Harry Maguire', 'Wesley Fofana'], ans: 1 },
  { id: 't16', cat: 'transfer', q: 'Which club did Erling Haaland leave to join Manchester City in 2022?', opts: ['RB Salzburg', 'Molde', 'Borussia Dortmund', 'Bayern Munich'], ans: 2 },
  { id: 't17', cat: 'transfer', q: 'Whose 2016 transfer to Manchester United held the world-record fee for one year, until it was smashed by Neymar\'s move in 2017?', opts: ['Paul Pogba', 'Gonzalo Higuaín', 'Kylian Mbappé', 'Ousmane Dembélé'], ans: 0 },
  { id: 't18', cat: 'transfer', q: 'Besides being the second most expensive transfer of all time, what other specific record does Kylian Mbappé\'s 2017 move to PSG hold?', opts: ['The most expensive teenager and the most expensive domestic transfer ever', 'The most expensive defender ever', 'The most expensive goalkeeper ever', 'The most expensive African player ever'], ans: 0 },
  { id: 't19', cat: 'transfer', q: 'In the summer of 2025, Liverpool broke the British transfer record for a second time in one window by signing which player?', opts: ['Alexander Isak', 'Florian Wirtz', 'Hugo Ekitike', 'Milos Kerkez'], ans: 0 },
  { id: 't20', cat: 'transfer', q: 'Which of these transfers is NOT currently among the top five most expensive of all time?', opts: ['Neymar to PSG', 'Kylian Mbappé to PSG', 'Alexander Isak to Liverpool', 'Cristiano Ronaldo to Real Madrid'], ans: 3 },

  { id: 'r01', cat: 'records', q: "How many Ballon d'Or awards has Lionel Messi won in total?", opts: ['6', '7', '8', '9'], ans: 2 },
  { id: 'r02', cat: 'records', q: 'Erling Haaland scored how many Premier League goals in his debut 2022-23 season?', opts: ['30', '33', '36', '38'], ans: 2 },
  { id: 'r03', cat: 'records', q: 'Which player holds the record for the most Premier League appearances?', opts: ['Ryan Giggs', 'Gareth Barry', 'James Milner', 'Frank Lampard'], ans: 1 },
  { id: 'r04', cat: 'records', q: 'Cristiano Ronaldo has won the UEFA Champions League how many times?', opts: ['4', '5', '6', '7'], ans: 1 },
  { id: 'r05', cat: 'records', q: 'Just Fontaine scored how many goals at the 1958 World Cup — still a single-tournament record?', opts: ['11', '12', '13', '15'], ans: 2 },
  { id: 'r06', cat: 'records', q: 'The fastest goal in Premier League history was scored in how many seconds?', opts: ['7.69', '9.82', '10.54', '12.4'], ans: 0 },
  { id: 'r07', cat: 'records', q: 'Which club won Bundesliga titles for a record nine consecutive seasons (2013-2022)?', opts: ['Borussia Dortmund', 'RB Leipzig', 'Bayer Leverkusen', 'Bayern Munich'], ans: 3 },
  { id: 'r08', cat: 'records', q: 'Who scored the fastest hat-trick in Premier League history (2 min 56 sec)?', opts: ['Robbie Fowler', 'Sadio Mané', 'Sergio Agüero', 'Alan Shearer'], ans: 1 },
  { id: 'r09', cat: 'records', q: 'Which nation has the most Copa América titles?', opts: ['Brazil', 'Argentina', 'Uruguay', 'Chile'], ans: 1 },
  { id: 'r10', cat: 'records', q: 'Bayer Leverkusen went unbeaten for how many Bundesliga games in 2023-24?', opts: ['32', '34', '36', '38'], ans: 1 },
  { id: 'r11', cat: 'records', q: "Lamine Yamal's goal at Euro 2024 made him the youngest scorer in Euros history, at what age?", opts: ['15', '16', '17', '18'], ans: 1 },
  { id: 'r12', cat: 'records', q: 'What is the highest number of goals scored in a single UEFA Champions League group stage game?', opts: ['10', '11', '12', '14'], ans: 2 },
  { id: 'r13', cat: 'records', q: "Who holds the men's record for most international appearances, having reached 233 caps for Portugal?", opts: ['Lionel Messi', 'Bader Al-Mutawa', 'Cristiano Ronaldo', 'Luka Modrić'], ans: 2 },
  { id: 'r14', cat: 'records', q: 'Which player holds the overall record for most international caps in football history (men\'s or women\'s), with 354 appearances for the USA?', opts: ['Christine Sinclair', 'Kristine Lilly', 'Carli Lloyd', 'Formiga'], ans: 1 },
  { id: 'r15', cat: 'records', q: "Who scored the fastest goal in men's World Cup history, netting after just 11 seconds against South Korea in 2002?", opts: ['Václav Mašek', 'Hakan Şükür', 'Bryan Robson', 'Clint Dempsey'], ans: 1 },
  { id: 'r16', cat: 'records', q: 'Which country recorded the biggest official win in men\'s international football history, beating American Samoa 31-0 in 2001?', opts: ['Brazil', 'Germany', 'Australia', 'Japan'], ans: 2 },
  { id: 'r17', cat: 'records', q: 'Who is the all-time top scorer in UEFA Champions League history, with 140 goals?', opts: ['Lionel Messi', 'Robert Lewandowski', 'Cristiano Ronaldo', 'Karim Benzema'], ans: 2 },
  { id: 'r18', cat: 'records', q: 'Robert Lewandowski became just the third player ever to score 100 UEFA Champions League goals — after Ronaldo and which other player?', opts: ['Karim Benzema', 'Lionel Messi', 'Thomas Müller', 'Raúl'], ans: 1 },
  { id: 'r19', cat: 'records', q: 'The 2025 Men\'s Ballon d\'Or winner, Ousmane Dembélé, was also named which official UEFA award that season after PSG\'s treble-winning campaign?', opts: ['UEFA Champions League Player of the Season', 'UEFA Men\'s Player of the Year', 'FIFA The Best', 'UEFA Golden Boot'], ans: 0 },
  { id: 'r20', cat: 'records', q: 'Who won the 2025 Women\'s Ballon d\'Or, claiming the award for a third consecutive year?', opts: ['Aitana Bonmatí', 'Alexia Putellas', 'Alessia Russo', 'Ada Hegerberg'], ans: 0 },
  { id: 'r21', cat: 'records', q: 'As of mid-2026, how many international caps does Cristiano Ronaldo have for Portugal, the current men\'s world record?', opts: ['226', '231', '233', '240'], ans: 2 },
  { id: 'r22', cat: 'records', q: 'Who was the first player in history to reach 100 UEFA Champions League goals, doing so in April 2017?', opts: ['Cristiano Ronaldo', 'Lionel Messi', 'Robert Lewandowski', 'Raúl'], ans: 0 },

  { id: 'tc01', cat: 'tactics', q: 'What does the "False 9" position refer to in modern football?', opts: ['A goalkeeper who plays outfield', 'A striker who drops deep to create space', 'A winger who cuts inside', 'A defender who pushes forward'], ans: 1 },
  { id: 'tc02', cat: 'tactics', q: 'Which formation is also known as the "Christmas Tree"?', opts: ['4-3-2-1', '3-4-3', '4-2-3-1', '5-3-2'], ans: 0 },
  { id: 'tc03', cat: 'tactics', q: 'What is the primary job of a "Libero" in football?', opts: ['Man-marking a striker', 'Sweeping behind the defensive line', 'Pressing high up the pitch', 'Covering the right flank'], ans: 1 },
  { id: 'tc04', cat: 'tactics', q: "Pep Guardiola's Barcelona teams were famous for which possession-based tactical system?", opts: ['Tiki-taka', 'Gegenpress', 'Park the bus', 'Catenaccio'], ans: 0 },
  { id: 'tc05', cat: 'tactics', q: 'The "Gegenpress" tactic was closely associated with which manager?', opts: ['Pep Guardiola', 'José Mourinho', 'Jürgen Klopp', 'Carlo Ancelotti'], ans: 2 },
  { id: 'tc06', cat: 'tactics', q: '"Catenaccio" is a defensive system most associated with which country?', opts: ['Spain', 'Germany', 'Italy', 'Brazil'], ans: 2 },
  { id: 'tc07', cat: 'tactics', q: 'What is an "inverted winger"?', opts: ['A winger who plays on the opposite foot and cuts inward', 'A winger who only defends', 'A forward who drops to left back', 'A winger who switches sides each half'], ans: 0 },
  { id: 'tc08', cat: 'tactics', q: 'In a 4-3-3, how many defensive players are there (excluding goalkeeper)?', opts: ['3', '4', '5', '6'], ans: 1 },
  { id: 'tc09', cat: 'tactics', q: 'What is the "pressing trap" tactic designed to do?', opts: ['Draw the opponent offside', 'Force the opponent into a predetermined zone to win the ball', 'Tire out the opponent by running without the ball', 'Create 2v1 situations on the wings'], ans: 1 },
  { id: 'tc10', cat: 'tactics', q: 'Which Italian club pioneered the use of a "three-at-the-back" system in the late 1980s and early 1990s?', opts: ['Juventus', 'Inter Milan', 'AC Milan', 'Roma'], ans: 2 },
  { id: 'tc11', cat: 'tactics', q: 'What term describes a modern goalkeeper who acts almost like an extra outfield player, sweeping up well outside the box behind a high defensive line?', opts: ['Sweeper-keeper', 'Libero', 'Regista', 'Trequartista'], ans: 0 },
  { id: 'tc12', cat: 'tactics', q: 'What Italian tactical term describes a deep-lying playmaker who dictates the tempo of play from a withdrawn midfield position?', opts: ['Trequartista', 'Regista', 'Mezzala', 'Incursore'], ans: 1 },
  { id: 'tc13', cat: 'tactics', q: 'The audacious "Panenka" penalty — a soft chip down the middle — is named after the player who famously scored one in a major final. In what competition and year?', opts: ['1974 World Cup final', '1976 Euro final', '1982 World Cup final', '1988 Euro final'], ans: 1 },
  { id: 'tc14', cat: 'tactics', q: 'What does "verticality" refer to in modern tactical analysis?', opts: ['Playing quick, direct forward passes to advance up the pitch rapidly', 'Switching play from flank to flank', 'Using tall strikers to win aerial duels', 'Playing with a back three'], ans: 0 },
  { id: 'tc15', cat: 'tactics', q: 'What is a "half-space," a term borrowed from German positional-play coaching theory?', opts: ['The width of the technical area', 'The vertical channel of the pitch between the wing and the central zone', 'The area directly in front of the penalty box', 'The zone reserved for a sweeper'], ans: 1 },
  { id: 'tc16', cat: 'tactics', q: 'What is a "double pivot" in football tactics?', opts: ['Two central defensive midfielders playing side-by-side to shield the defense', 'Two strikers rotating positions', 'A formation using two sweeper-keepers', 'A tactical double substitution at half time'], ans: 0 },

  { id: 'p01', cat: 'players', q: 'Which country does Rodri (Rodrigo Hernández) play international football for?', opts: ['Argentina', 'Portugal', 'Spain', 'Brazil'], ans: 2 },
  { id: 'p02', cat: 'players', q: 'Khvicha Kvaratskhelia — nicknamed "Kvaradona" — plays for which national team?', opts: ['Armenia', 'Ukraine', 'Azerbaijan', 'Georgia'], ans: 3 },
  { id: 'p03', cat: 'players', q: 'Which club did Pedri leave at age 17 to join FC Barcelona?', opts: ['Villarreal', 'Las Palmas', 'Getafe', 'Osasuna'], ans: 1 },
  { id: 'p04', cat: 'players', q: 'Brahim Díaz switched international allegiance from Spain to which nation?', opts: ['Algeria', 'Tunisia', 'Morocco', 'Egypt'], ans: 2 },
  { id: 'p05', cat: 'players', q: 'Who won the 2024 Ballon d\'Or?', opts: ['Vinicius Jr.', 'Erling Haaland', 'Rodri', 'Kylian Mbappé'], ans: 2 },
  { id: 'p06', cat: 'players', q: 'Florian Wirtz came through the academy of which Bundesliga club?', opts: ['Bayern Munich', 'Borussia Dortmund', 'Bayer Leverkusen', 'RB Leipzig'], ans: 2 },
  { id: 'p07', cat: 'players', q: 'Which position does Trent Alexander-Arnold play?', opts: ['Left-back', 'Centre-back', 'Right-back', 'Defensive midfielder'], ans: 2 },
  { id: 'p08', cat: 'players', q: 'Federico Valverde was born in Montevideo and plays for which national team?', opts: ['Argentina', 'Uruguay', 'Paraguay', 'Chile'], ans: 1 },
  { id: 'p09', cat: 'players', q: 'Victor Osimhen joined Napoli from which French club?', opts: ['Marseille', 'Nice', 'Lille', 'Lyon'], ans: 2 },
  { id: 'p10', cat: 'players', q: "Alejandro Garnacho developed at Manchester United having left which Spanish club's youth academy?", opts: ['Real Madrid', 'Atlético Madrid', 'Getafe', 'Rayo Vallecano'], ans: 1 },
  { id: 'p11', cat: 'players', q: 'Wataru Endō captains which national team?', opts: ['South Korea', 'China', 'Australia', 'Japan'], ans: 3 },
  { id: 'p12', cat: 'players', q: 'Which player is nicknamed "La Pulga" (The Flea)?', opts: ['Neymar', 'Lionel Messi', 'Andrés Iniesta', 'Cesc Fàbregas'], ans: 1 },
  { id: 'p13', cat: 'players', q: 'Joshua Kimmich can play right-back, but which position does he predominantly fill at Bayern Munich?', opts: ['Attacking midfielder', 'Left winger', 'Defensive midfielder', 'Centre-back'], ans: 2 },
  { id: 'p14', cat: 'players', q: 'Lamine Yamal represents which country?', opts: ['Morocco', 'France', 'Spain', 'Algeria'], ans: 2 },
  { id: 'p15', cat: 'players', q: 'Who was named Player of the Tournament at the 2022 FIFA World Cup?', opts: ['Kylian Mbappé', 'Lionel Messi', 'Julián Álvarez', 'Luka Modric'], ans: 1 },
  { id: 'p16', cat: 'players', q: 'Which player is the only goalkeeper ever to have won the Ballon d\'Or, back in 1963?', opts: ['Dino Zoff', 'Lev Yashin', 'Gordon Banks', 'Peter Shilton'], ans: 1 },
  { id: 'p17', cat: 'players', q: 'Who captained Italy to the 1982 World Cup title as goalkeeper, becoming, at 40, the oldest player to win the World Cup?', opts: ['Dino Zoff', 'Walter Zenga', 'Gianluigi Buffon', 'Giovanni Trapattoni'], ans: 0 },
  { id: 'p18', cat: 'players', q: 'Which Chilean player received the first-ever red card in FIFA World Cup history, sent off against West Germany in 1974?', opts: ['Alexis Sánchez', 'Carlos Caszely', 'Elías Figueroa', 'Iván Zamorano'], ans: 1 },
  { id: 'p19', cat: 'players', q: 'French forward Lucien Laurent is remembered in football history for what feat?', opts: ['Scoring the first hat-trick in World Cup history', 'Scoring the first-ever FIFA World Cup goal, in 1930', 'Scoring the first penalty in a World Cup final', 'Scoring the first own goal in World Cup history'], ans: 1 },
  { id: 'p20', cat: 'players', q: 'Robert Lewandowski became the first Polish player to achieve what feat in UEFA Champions League history, doing so with Bayern Munich in 2019-20?', opts: ['Win the competition as captain', 'Finish as the competition\'s outright top scorer in a season', 'Score in every group-stage game', 'Play for four different clubs in the competition'], ans: 1 },
  { id: 'p21', cat: 'players', q: 'Which position does Vitinha primarily play for Paris Saint-Germain and Portugal?', opts: ['Central midfielder', 'Right-back', 'Winger', 'Striker'], ans: 0 },
  { id: 'p22', cat: 'players', q: 'Before signing for Borussia Dortmund, Ousmane Dembélé began his professional career at which French club?', opts: ['Rennes', 'Lyon', 'Lille', 'Marseille'], ans: 0 },
  { id: 'p23', cat: 'players', q: 'Which player scored the second-fastest hat-trick in UEFA Champions League history, netting three times in seven minutes away at Olympiacos in the 2025-26 season?', opts: ['Kylian Mbappé', 'Vinícius Júnior', 'Jude Bellingham', 'Rodrygo'], ans: 0 },
  { id: 'p24', cat: 'players', q: 'Viktor Gyökeres won the Gerd Müller Trophy for most goals scored in the 2024-25 season while playing for which club for most of that campaign?', opts: ['Sporting CP', 'Arsenal', 'Benfica', 'Porto'], ans: 0 },

  { id: 's01', cat: 'stadiums', q: 'In which city is the Santiago Bernabéu stadium located?', opts: ['Barcelona', 'Seville', 'Valencia', 'Madrid'], ans: 3 },
  { id: 's02', cat: 'stadiums', q: 'The Maracanã stadium is in which Brazilian city?', opts: ['São Paulo', 'Brasília', 'Rio de Janeiro', 'Salvador'], ans: 2 },
  { id: 's03', cat: 'stadiums', q: 'Which stadium hosted the 2022 FIFA World Cup final?', opts: ['Al Bayt Stadium', 'Khalifa International Stadium', 'Lusail Stadium', 'Al Janoub Stadium'], ans: 2 },
  { id: 's04', cat: 'stadiums', q: "What is the name of Borussia Dortmund's iconic stadium?", opts: ['Allianz Arena', 'Signal Iduna Park', 'Red Bull Arena', 'Commerzbank Arena'], ans: 1 },
  { id: 's05', cat: 'stadiums', q: 'Camp Nou is being redeveloped — which club plays there?', opts: ['Atlético Madrid', 'Real Madrid', 'FC Barcelona', 'Valencia'], ans: 2 },
  { id: 's06', cat: 'stadiums', q: 'Which stadium is known as "The Theatre of Dreams"?', opts: ['Anfield', 'Stamford Bridge', 'Old Trafford', 'Tottenham Hotspur Stadium'], ans: 2 },
  { id: 's07', cat: 'stadiums', q: 'The Allianz Arena is home to which German club?', opts: ['Borussia Dortmund', 'RB Leipzig', 'Bayer Leverkusen', 'Bayern Munich'], ans: 3 },
  { id: 's08', cat: 'stadiums', q: 'Which stadium has the largest capacity in world football?', opts: ['Camp Nou', 'Wembley', 'Narendra Modi Stadium', 'Rungrado 1st of May'], ans: 3 },
  { id: 's09', cat: 'stadiums', q: 'Anfield is home to which Premier League club?', opts: ['Manchester City', 'Everton', 'Liverpool', 'Newcastle United'], ans: 2 },
  { id: 's10', cat: 'stadiums', q: 'Where did the 2023 UEFA Champions League final take place?', opts: ['Wembley', 'Atatürk Olympic Stadium', 'Olimpico', 'Stade de France'], ans: 0 },
  { id: 's11', cat: 'stadiums', q: 'What is the official capacity of Wembley Stadium, home of the England national team?', opts: ['Around 60,000', 'Around 75,000', 'Around 90,000', 'Around 100,000'], ans: 2 },
  { id: 's12', cat: 'stadiums', q: 'San Siro (officially the Stadio Giuseppe Meazza) in Milan is the shared home of which two clubs?', opts: ['Inter Milan and Juventus', 'AC Milan and Inter Milan', 'AC Milan and Roma', 'Inter Milan and Napoli'], ans: 1 },
  { id: 's13', cat: 'stadiums', q: "Which stadium, home to the Bolivian national team, is one of the highest-altitude venues in world football at roughly 3,600 metres above sea level?", opts: ['Estadio Nacional (Lima)', 'Estadio Hernando Siles (La Paz)', 'Estadio Monumental (Lima)', 'Estadio Centenario (Montevideo)'], ans: 1 },
  { id: 's14', cat: 'stadiums', q: 'Which stadium is hosting the final of the 2026 FIFA World Cup?', opts: ['MetLife Stadium (New Jersey)', 'SoFi Stadium (Los Angeles)', 'Estadio Azteca (Mexico City)', 'AT&T Stadium (Dallas)'], ans: 0 },
  { id: 's15', cat: 'stadiums', q: 'The 2026 World Cup opening match was hosted by a historic stadium that became the first venue ever to host three World Cups. Which one?', opts: ['Estadio Azteca (Mexico City Stadium)', 'Maracanã', 'Wembley', 'Rose Bowl'], ans: 0 },
  { id: 's16', cat: 'stadiums', q: 'Mexico City\'s Estadio Azteca sits at roughly what altitude above sea level, a factor often cited as an advantage for the host nation?', opts: ['1,200 metres', '1,800 metres', '2,200 metres', '3,600 metres'], ans: 2 },
  { id: 's17', cat: 'stadiums', q: 'The 2026 World Cup final at MetLife Stadium will feature a first in the tournament\'s history. What is it?', opts: ['A half-time show, similar to the NFL Super Bowl', 'A golden-goal decider', 'A sixth substitute allowed', 'Fully automated, VAR-free officiating'], ans: 0 },

  { id: 'm01', cat: 'managers', q: 'Which manager led Liverpool to Champions League glory in 2019?', opts: ['Brendan Rodgers', 'Rafa Benítez', 'Jürgen Klopp', 'Kenny Dalglish'], ans: 2 },
  { id: 'm02', cat: 'managers', q: 'Who is the most decorated manager in English football history by trophies won?', opts: ['José Mourinho', 'Pep Guardiola', 'Alex Ferguson', 'Arsène Wenger'], ans: 2 },
  { id: 'm03', cat: 'managers', q: 'Pep Guardiola won the treble with Barcelona, Bayern Munich, and Manchester City. Which came first?', opts: ['Bayern Munich treble', 'Barcelona treble', 'Manchester City treble', 'He has not won with Bayern'], ans: 1 },
  { id: 'm04', cat: 'managers', q: 'José Mourinho famously dubbed himself "The Special One" in 2004 at which club?', opts: ['Inter Milan', 'Real Madrid', 'Chelsea', 'Manchester United'], ans: 2 },
  { id: 'm05', cat: 'managers', q: 'Which manager guided Argentina to their 2022 World Cup triumph?', opts: ['Gerardo Martino', 'Edgardo Bauza', 'Lionel Scaloni', 'Jorge Sampaoli'], ans: 2 },
  { id: 'm06', cat: 'managers', q: 'Xabi Alonso led Bayer Leverkusen to their first-ever Bundesliga title in which season?', opts: ['2022-23', '2023-24', '2024-25', '2021-22'], ans: 1 },
  { id: 'm07', cat: 'managers', q: 'Who managed France when they won the 2018 World Cup?', opts: ['Raymond Domenech', 'Laurent Blanc', 'Didier Deschamps', 'Guy Roux'], ans: 2 },
  { id: 'm08', cat: 'managers', q: 'Carlo Ancelotti has won a record five UEFA Champions League titles — but with how many different clubs?', opts: ['2', '3', '4', '1'], ans: 0 },
  { id: 'm09', cat: 'managers', q: 'Which manager\'s "Gegenpressing" system made Liverpool into Premier League and European champions?', opts: ['Pep Guardiola', 'Jürgen Klopp', 'Thomas Tuchel', 'Roberto Mancini'], ans: 1 },
  { id: 'm10', cat: 'managers', q: 'Mikel Arteta played for Arsenal and managed which club before returning to the Emirates?', opts: ['Everton', 'Manchester City', 'PSG', 'Villarreal'], ans: 1 },
  { id: 'm11', cat: 'managers', q: 'Which two clubs has Carlo Ancelotti won the UEFA Champions League with?', opts: ['AC Milan and Real Madrid', 'Chelsea and Real Madrid', 'AC Milan and Bayern Munich', 'Real Madrid and Napoli'], ans: 0 },
  { id: 'm12', cat: 'managers', q: 'Carlo Ancelotti became the first manager in history to win a league title in each of which set of leagues?', opts: ["Europe's 'big five' domestic leagues", 'Every UEFA confederation league', 'Both the Premier League and MLS', 'All four English divisions'], ans: 0 },
  { id: 'm13', cat: 'managers', q: 'Which manager has won the Champions League with two different clubs — Porto and Inter Milan?', opts: ['José Mourinho', 'Carlo Ancelotti', 'Pep Guardiola', 'Zinedine Zidane'], ans: 0 },
  { id: 'm14', cat: 'managers', q: 'Xabi Alonso\'s stint as Real Madrid head coach ended after just seven months when the club parted ways with him in January 2026. Who replaced him?', opts: ['Álvaro Arbeloa', 'Santiago Solari', 'Zinedine Zidane', 'Raúl González'], ans: 0 },
  { id: 'm15', cat: 'managers', q: 'Which club appointed Xabi Alonso as its new manager, starting from July 2026, four months after his Real Madrid exit?', opts: ['Chelsea', 'Bayern Munich', 'Liverpool', 'Tottenham Hotspur'], ans: 0 },
  { id: 'm16', cat: 'managers', q: 'Which manager won the Men\'s Johan Cruyff Trophy for best coach at the 2025 Ballon d\'Or, after leading PSG to a historic quadruple?', opts: ['Luis Enrique', 'Carlo Ancelotti', 'Xabi Alonso', 'Hansi Flick'], ans: 0 },

  { id: 'ru01', cat: 'rules', q: 'How many substitutes is a team allowed to use in a standard FIFA-approved match?', opts: ['3', '4', '5', '6'], ans: 2 },
  { id: 'ru02', cat: 'rules', q: 'VAR (Video Assistant Referee) was first used at which World Cup?', opts: ['2014', '2018', '2022', '2010'], ans: 1 },
  { id: 'ru03', cat: 'rules', q: 'How many minutes is added for each substitution made in a game under current IFAB rules?', opts: ['30 seconds', '1 minute', '2 minutes', 'None — it is umpire\'s discretion'], ans: 1 },
  { id: 'ru04', cat: 'rules', q: 'What is the minimum distance an opposition player must stand from the ball at a free kick?', opts: ['7.3 m', '9.15 m', '10 m', '11 m'], ans: 1 },
  { id: 'ru05', cat: 'rules', q: 'Under the offside rule, which body parts are used to judge offside position?', opts: ['Any body part except hands/arms', 'Only the feet', 'Any body part except the head', 'Head and torso only'], ans: 0 },
  { id: 'ru06', cat: 'rules', q: 'What happens if a goalkeeper saves a penalty but is judged to have moved off the line too early?', opts: ['Goal awarded', 'Penalty is retaken', 'Free kick to the attacking team', 'Yellow card only'], ans: 1 },
  { id: 'ru07', cat: 'rules', q: 'How long does each half of extra time last?', opts: ['10 minutes', '15 minutes', '20 minutes', '30 minutes'], ans: 1 },
  { id: 'ru08', cat: 'rules', q: 'A player receives a straight red card. How many matches is the standard suspension?', opts: ['1', '2', '3', '5'], ans: 2 },
  { id: 'ru09', cat: 'rules', q: 'When was the back-pass rule introduced — making it illegal for a goalkeeper to pick up a deliberate pass from a teammate?', opts: ['1988', '1990', '1992', '1994'], ans: 2 },
  { id: 'ru10', cat: 'rules', q: 'How large is a standard football goal (in metres, width × height)?', opts: ['6.4m × 2.2m', '7.32m × 2.44m', '8m × 2.5m', '7m × 2.4m'], ans: 1 },
  { id: 'ru11', cat: 'rules', q: 'Yellow and red disciplinary cards were introduced to football at which World Cup?', opts: ['1966', '1970', '1974', '1978'], ans: 1 },
  { id: 'ru12', cat: 'rules', q: 'In what year was the offside law changed to require only two defenders (rather than three) between the attacker and the goal line?', opts: ['1907', '1925', '1938', '1950'], ans: 1 },
  { id: 'ru13', cat: 'rules', q: 'UEFA abolished its long-standing "away goals" rule for two-legged club competition ties in which year?', opts: ['2018', '2019', '2020', '2021'], ans: 3 },
  { id: 'ru14', cat: 'rules', q: 'Starting with the 2025/26 Laws of the Game, for how many seconds can a goalkeeper now hold the ball before conceding a corner kick to the opposition?', opts: ['6 seconds', '7 seconds', '8 seconds', '10 seconds'], ans: 2 },
  { id: 'ru15', cat: 'rules', q: 'IFAB\'s "Only the Captain" protocol, folded into the Laws of the Game for 2025/26, restricts who may approach the referee during major decisions?', opts: ['Only the team captain', 'Any outfield player', 'The vice-captain and captain', 'Only the goalkeeper'], ans: 0 },
  { id: 'ru16', cat: 'rules', q: 'Under the new 2025/26 goalkeeper time-limit rule, what does the referee do in the final moments before a corner is awarded?', opts: ['Visually count down the last five seconds with a raised hand', 'Blow a warning whistle at three seconds', 'Automatically show a yellow card', 'Stop the match clock'], ans: 0 },
];

export const RAPID_FIRE_QUESTIONS = [

  { q: 'Achraf Hakimi was born in Madrid but represents which nation?', type: 'country', opts: ['Spain', 'Morocco', 'Algeria', 'France'], ans: 1 },
  { q: 'Lautaro Martínez wears the armband for which national team?', type: 'country', opts: ['Uruguay', 'Colombia', 'Chile', 'Argentina'], ans: 3 },
  { q: 'João Félix holds a passport from which country?', type: 'country', opts: ['Spain', 'Brazil', 'Portugal', 'Cape Verde'], ans: 2 },
  { q: 'Khvicha Kvaratskhelia represents which former Soviet republic?', type: 'country', opts: ['Armenia', 'Azerbaijan', 'Ukraine', 'Georgia'], ans: 3 },
  { q: 'Florian Wirtz plays international football for which nation?', type: 'country', opts: ['Austria', 'Switzerland', 'Germany', 'Netherlands'], ans: 2 },
  { q: 'Rúben Dias plays international football for which country?', type: 'country', opts: ['Spain', 'Brazil', 'Portugal', 'Angola'], ans: 2 },
  { q: 'Which nation does Julián Álvarez represent?', type: 'country', opts: ['Mexico', 'Colombia', 'Uruguay', 'Argentina'], ans: 3 },
  { q: 'Wataru Endō captains which national side?', type: 'country', opts: ['South Korea', 'China', 'Japan', 'Australia'], ans: 2 },
  { q: 'Federico Valverde was born in Montevideo and represents…', type: 'country', opts: ['Argentina', 'Uruguay', 'Paraguay', 'Chile'], ans: 1 },
  { q: 'Brahim Díaz switched international allegiance from Spain to which country?', type: 'country', opts: ['Algeria', 'Tunisia', 'Senegal', 'Morocco'], ans: 3 },
  { q: 'Erling Haaland represents which national team?', type: 'country', opts: ['Sweden', 'Denmark', 'Norway', 'Iceland'], ans: 2 },
  { q: 'Bukayo Saka represents which national team?', type: 'country', opts: ['Nigeria', 'England', 'Ghana', 'Ireland'], ans: 1 },
  { q: 'Which country does Pedri represent internationally?', type: 'country', opts: ['Portugal', 'Spain', 'Morocco', 'France'], ans: 1 },


  { q: 'Erling Haaland left Borussia Dortmund for Manchester City in which year?', type: 'club', opts: ['2021', '2022', '2023', '2024'], ans: 1 },
  { q: 'From which club did Chelsea sign Enzo Fernández in January 2023?', type: 'club', opts: ['River Plate', 'Ajax', 'Benfica', 'PSV'], ans: 2 },
  { q: 'Before joining Arsenal, Declan Rice was captain of which club?', type: 'club', opts: ['Tottenham', 'West Ham United', 'Everton', 'Leicester City'], ans: 1 },
  { q: 'Jude Bellingham moved to Real Madrid from which Bundesliga club?', type: 'club', opts: ['RB Leipzig', 'Bayern Munich', 'Bayer Leverkusen', 'Borussia Dortmund'], ans: 3 },
  { q: 'Which club sold Gavi through its famous La Masia academy?', type: 'club', opts: ['Real Madrid', 'Atlético Madrid', 'Barcelona', 'Valencia'], ans: 2 },
  { q: 'Alejandro Garnacho joined Manchester United\'s academy from which city\'s club?', type: 'club', opts: ['Barcelona', 'Atlético Madrid', 'Real Madrid', 'Getafe'], ans: 1 },
  { q: 'Kylian Mbappé spent a loan season early in his career at which club?', type: 'club', opts: ['Nice', 'Monaco', 'Caen', 'Lens'], ans: 1 },
  { q: 'Mohamed Salah was at which Italian club before joining Liverpool?', type: 'club', opts: ['Inter Milan', 'AC Milan', 'Juventus', 'Roma'], ans: 3 },
  { q: 'Victor Osimhen joined Napoli from which French club?', type: 'club', opts: ['Marseille', 'Lyon', 'Lille', 'Nice'], ans: 2 },
  { q: 'Which club did Pedri leave to join Barcelona as a 17-year-old?', type: 'club', opts: ['Villarreal', 'Las Palmas', 'Sporting Gijón', 'Granada'], ans: 1 },
  { q: 'Lamine Yamal is a product of which club\'s academy?', type: 'club', opts: ['Real Madrid', 'Atlético Madrid', 'Espanyol', 'Barcelona'], ans: 3 },
  { q: 'Which English club did Ivan Toney leave to join Al-Ahli in 2024?', type: 'club', opts: ['Crystal Palace', 'Brentford', 'Nottingham Forest', 'Fulham'], ans: 1 },
  { q: 'Which boyhood club did Neymar rejoin in 2025, having left as a teenager back in 2013?', type: 'club', opts: ['Corinthians', 'Flamengo', 'Santos', 'São Paulo'], ans: 2 },
  { q: 'Which club did Kevin De Bruyne leave as a free agent in 2025 after nearly a decade there?', type: 'club', opts: ['Chelsea', 'Wolfsburg', 'Manchester City', 'Werder Bremen'], ans: 2 },


  { q: 'What position does Trent Alexander-Arnold typically play for Liverpool?', type: 'position', opts: ['Left-back', 'Centre-back', 'Right-back', 'Defensive midfielder'], ans: 2 },
  { q: 'Rodri plays as what kind of midfielder for Manchester City?', type: 'position', opts: ['Attacking midfielder', 'Defensive midfielder', 'Box-to-box', 'Second striker'], ans: 1 },
  { q: 'In what position does Lautaro Martínez play at Inter Milan?', type: 'position', opts: ['False 9', 'Centre-forward', 'Left winger', 'Attacking midfielder'], ans: 1 },
  { q: 'Dani Carvajal plays in which position for Real Madrid?', type: 'position', opts: ['Left-back', 'Right-back', 'Central midfielder', 'Left winger'], ans: 1 },
  { q: 'Joshua Kimmich can play right-back but predominantly plays as what at Bayern Munich?', type: 'position', opts: ['Attacking midfielder', 'Winger', 'Defensive midfielder', 'Sweeper'], ans: 2 },
  { q: 'Rúben Dias is an elite practitioner of which position?', type: 'position', opts: ['Goalkeeper', 'Defensive midfielder', 'Centre-back', 'Right-back'], ans: 2 },
  { q: 'Bukayo Saka usually starts from which flank for Arsenal?', type: 'position', opts: ['Left wing', 'Right wing', 'Left-back', 'Centre-forward'], ans: 1 },
  { q: 'What is Casemiro\'s primary position?', type: 'position', opts: ['Centre-back', 'Right midfielder', 'Defensive midfielder', 'Attacking midfielder'], ans: 2 },
  { q: 'What position does Virgil van Dijk play?', type: 'position', opts: ['Right-back', 'Defensive midfielder', 'Centre-back', 'Goalkeeper'], ans: 2 },
  { q: 'What is Alisson Becker\'s position?', type: 'position', opts: ['Centre-back', 'Goalkeeper', 'Right-back', 'Defensive midfielder'], ans: 1 },


  { q: 'How many Ballon d\'Or awards has Lionel Messi won?', type: 'fact', opts: ['6', '7', '8', '9'], ans: 2 },
  { q: 'Erling Haaland scored how many Premier League goals in his debut season (2022-23)?', type: 'fact', opts: ['30', '33', '36', '38'], ans: 2 },
  { q: 'Which player won the 2023 Ballon d\'Or?', type: 'fact', opts: ['Kylian Mbappé', 'Erling Haaland', 'Vinicius Jr.', 'Lionel Messi'], ans: 3 },
  { q: 'Which player won the 2024 Ballon d\'Or?', type: 'fact', opts: ['Vinicius Jr.', 'Rodri', 'Erling Haaland', 'Kylian Mbappé'], ans: 1 },
  { q: 'In which year did Man City complete an unprecedented English treble?', type: 'fact', opts: ['2019', '2021', '2022', '2023'], ans: 3 },
  { q: 'Which club has won the most UEFA Champions League titles?', type: 'fact', opts: ['Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Munich'], ans: 2 },
  { q: 'Who holds the record for most goals scored in a single World Cup tournament?', type: 'fact', opts: ['Ronaldo (Brazil)', 'Miroslav Klose', 'Gerd Müller', 'Just Fontaine'], ans: 3 },
  { q: 'What is the maximum squad size allowed in a FIFA World Cup final tournament?', type: 'fact', opts: ['23', '25', '26', '28'], ans: 2 },
  { q: 'Who was the first player ever to win five Ballon d\'Or awards?', type: 'fact', opts: ['Cristiano Ronaldo', 'Lionel Messi', 'Ronaldo (Brazil)', 'Zinedine Zidane'], ans: 1 },
  { q: 'Which stadium has the largest official capacity in world football?', type: 'fact', opts: ['Camp Nou', 'Wembley', 'Narendra Modi Stadium', 'Rungrado 1st of May'], ans: 3 },
  { q: 'Kylian Mbappé became the youngest French player to score at a World Cup at what age?', type: 'fact', opts: ['18', '19', '20', '21'], ans: 1 },
  { q: 'Who scored the fastest hat-trick in Premier League history (2 min 56 sec)?', type: 'fact', opts: ['Robbie Fowler', 'Sadio Mané', 'Sergio Agüero', 'Michael Owen'], ans: 1 },
  { q: 'Which country has won the Copa América the most times?', type: 'fact', opts: ['Brazil', 'Argentina', 'Uruguay', 'Chile'], ans: 1 },
  { q: 'VAR was introduced at which FIFA World Cup?', type: 'fact', opts: ['2014', '2018', '2022', '2010'], ans: 1 },
  { q: 'Which league does Al-Nassr compete in?', type: 'fact', opts: ['UAE Pro League', 'Saudi Pro League', 'Qatar Stars League', 'Egyptian Premier League'], ans: 1 },
  { q: 'Lamine Yamal became the youngest scorer in Euro history at what age at Euro 2024?', type: 'fact', opts: ['16', '17', '18', '15'], ans: 0 },
  { q: 'Which club did Bayer Leverkusen go the entire 2023-24 Bundesliga season unbeaten to deny?', type: 'fact', opts: ['Bayern Munich', 'Borussia Dortmund', 'RB Leipzig', 'Stuttgart'], ans: 0 },
  { q: 'How many times has Cristiano Ronaldo won the UEFA Champions League?', type: 'fact', opts: ['4', '5', '6', '7'], ans: 1 },
  { q: 'Neymar\'s move to PSG in 2017 remains the outright world-record football transfer fee — how much was it?', type: 'fact', opts: ['€180m', '€200m', '€222m', '€250m'], ans: 2 },
  { q: 'Which goalkeeper is the only one ever to win the Ballon d\'Or?', type: 'fact', opts: ['Gianluigi Buffon', 'Iker Casillas', 'Manuel Neuer', 'Lev Yashin'], ans: 3 },
  { q: 'Who scored the first-ever goal in FIFA World Cup history, in 1930?', type: 'fact', opts: ['Guillermo Stábile', 'Lucien Laurent', 'Bert Patenaude', 'Héctor Castro'], ans: 1 },
  { q: 'Which country recorded a staggering 31-0 win in World Cup qualifying in 2001?', type: 'fact', opts: ['Germany', 'Australia', 'Brazil', 'Iran'], ans: 1 },
  { q: 'Who is the all-time top scorer in UEFA Champions League history?', type: 'fact', opts: ['Lionel Messi', 'Cristiano Ronaldo', 'Robert Lewandowski', 'Karim Benzema'], ans: 1 },
];

export const TOP10_QUESTIONS = [
  {
    id: 't10_01',
    question: "All-Time Premier League Top Goalscorers",
    answers: [
      { name: "Alan Shearer", value: "260 goals", accepts: ["alan shearer", "shearer"] },
      { name: "Harry Kane", value: "213 goals", accepts: ["harry kane", "kane"] },
      { name: "Wayne Rooney", value: "208 goals", accepts: ["wayne rooney", "rooney"] },
      { name: "Andy Cole", value: "187 goals", accepts: ["andy cole", "andrew cole", "cole"] },
      { name: "Sergio Agüero", value: "184 goals", accepts: ["sergio aguero", "aguero", "sergio agüero", "agüero"] },
      { name: "Frank Lampard", value: "177 goals", accepts: ["frank lampard", "lampard"] },
      { name: "Thierry Henry", value: "175 goals", accepts: ["thierry henry", "henry"] },
      { name: "Robbie Fowler", value: "163 goals", accepts: ["robbie fowler", "fowler"] },
      { name: "Jermain Defoe", value: "162 goals", accepts: ["jermain defoe", "defoe"] },
      { name: "Mohamed Salah", value: "157 goals", accepts: ["mohamed salah", "salah", "mo salah"] }
    ]
  },
  {
    id: 't10_02',
    question: "Clubs with the Most Champions League / European Cup Titles",
    answers: [
      { name: "Real Madrid", value: "15 titles", accepts: ["real madrid", "madrid"] },
      { name: "AC Milan", value: "7 titles", accepts: ["ac milan", "milan"] },
      { name: "Bayern Munich", value: "6 titles", accepts: ["bayern munich", "bayern", "munich", "bayern munchen"] },
      { name: "Liverpool", value: "6 titles", accepts: ["liverpool"] },
      { name: "Barcelona", value: "5 titles", accepts: ["barcelona", "barca"] },
      { name: "Ajax", value: "4 titles", accepts: ["ajax"] },
      { name: "Manchester United", value: "3 titles", accepts: ["manchester united", "man utd", "man united"] },
      { name: "Inter Milan", value: "3 titles", accepts: ["inter milan", "inter", "internazionale", "inter de milan"] },
      { name: "Juventus", value: "2 titles", accepts: ["juventus", "juve"] },
      { name: "Chelsea", value: "2 titles", accepts: ["chelsea"] }
    ]
  },
  {
    id: 't10_03',
    question: "Ballon d'Or Most Wins (Players)",
    answers: [
      { name: "Lionel Messi", value: "8 wins", accepts: ["lionel messi", "messi", "leo messi"] },
      { name: "Cristiano Ronaldo", value: "5 wins", accepts: ["cristiano ronaldo", "ronaldo", "cristiano", "cr7"] },
      { name: "Johan Cruyff", value: "3 wins", accepts: ["johan cruyff", "cruyff", "cruijff"] },
      { name: "Michel Platini", value: "3 wins", accepts: ["michel platini", "platini"] },
      { name: "Marco van Basten", value: "3 wins", accepts: ["marco van basten", "van basten"] },
      { name: "Franz Beckenbauer", value: "2 wins", accepts: ["franz beckenbauer", "beckenbauer"] },
      { name: "Ronaldo Nazário", value: "2 wins", accepts: ["ronaldo nazario", "ronaldo", "r9", "phenomenon"] },
      { name: "Alfredo Di Stéfano", value: "2 wins", accepts: ["alfredo di stefano", "di stefano"] },
      { name: "Kevin Keegan", value: "2 wins", accepts: ["kevin keegan", "keegan"] },
      { name: "Karl-Heinz Rummenigge", value: "2 wins", accepts: ["karl-heinz rummenigge", "rummenigge"] }
    ]
  },
  {
    id: 't10_04',
    question: "Most Expensive Football Transfers of All Time (mid-2026)",
    answers: [
      { name: "Neymar (Barcelona to PSG)", value: "€222m", accepts: ["neymar", "neymar jr"] },
      { name: "Kylian Mbappé (Monaco to PSG)", value: "€180m", accepts: ["kylian mbappe", "mbappe", "mbappé"] },
      { name: "Alexander Isak (Newcastle to Liverpool)", value: "€144.5m", accepts: ["alexander isak", "isak"] },
      { name: "João Félix (Benfica to Atlético Madrid)", value: "€126m", accepts: ["joao felix", "felix", "joão felix", "joão félix"] },
      { name: "Enzo Fernández (Benfica to Chelsea)", value: "€121m", accepts: ["enzo fernandez", "enzo", "fernandez"] },
      { name: "Antoine Griezmann (Atlético Madrid to Barcelona)", value: "€120m", accepts: ["antoine griezmann", "griezmann"] },
      { name: "Philippe Coutinho (Liverpool to Barcelona)", value: "€118.4m", accepts: ["philippe coutinho", "coutinho"] },
      { name: "Jack Grealish (Aston Villa to Man City)", value: "€117.7m", accepts: ["jack grealish", "grealish"] },
      { name: "Florian Wirtz (Bayer Leverkusen to Liverpool)", value: "€117.5m", accepts: ["florian wirtz", "wirtz"] },
      { name: "Declan Rice (West Ham to Arsenal)", value: "€116.5m", accepts: ["declan rice", "rice"] }
    ]
  },
  {
    id: 't10_05',
    question: "Players with the Most UEFA Champions League Appearances",
    answers: [
      { name: "Cristiano Ronaldo", value: "183 appearances", accepts: ["cristiano ronaldo", "ronaldo", "cr7"] },
      { name: "Iker Casillas", value: "177 appearances", accepts: ["iker casillas", "casillas"] },
      { name: "Lionel Messi", value: "163 appearances", accepts: ["lionel messi", "messi", "leo messi"] },
      { name: "Karim Benzema", value: "152 appearances", accepts: ["karim benzema", "benzema"] },
      { name: "Toni Kroos", value: "151 appearances", accepts: ["toni kroos", "kroos"] },
      { name: "Thomas Müller", value: "151 appearances", accepts: ["thomas muller", "muller", "thomas müller", "müller"] },
      { name: "Xavi", value: "151 appearances", accepts: ["xavi", "xavi / xavi hernandez", "xavi hernandez"] },
      { name: "Ryan Giggs", value: "145 appearances", accepts: ["ryan giggs", "giggs"] },
      { name: "Raúl", value: "142 appearances", accepts: ["raul", "raúl"] },
      { name: "Sergio Ramos", value: "142 appearances", accepts: ["sergio ramos", "ramos"] }
    ]
  },
  {
    id: 't10_06',
    question: "Clubs with the Most English Premier League / First Division Titles",
    answers: [
      { name: "Manchester United", value: "20 titles", accepts: ["manchester united", "man utd", "man united"] },
      { name: "Liverpool", value: "20 titles", accepts: ["liverpool"] },
      { name: "Arsenal", value: "13 titles", accepts: ["arsenal"] },
      { name: "Manchester City", value: "10 titles", accepts: ["manchester city", "man city", "city"] },
      { name: "Everton", value: "9 titles", accepts: ["everton"] },
      { name: "Aston Villa", value: "7 titles", accepts: ["aston villa", "villa"] },
      { name: "Sunderland", value: "6 titles", accepts: ["sunderland"] },
      { name: "Chelsea", value: "6 titles", accepts: ["chelsea"] },
      { name: "Newcastle United", value: "4 titles", accepts: ["newcastle united", "newcastle"] },
      { name: "Sheffield Wednesday", value: "4 titles", accepts: ["sheffield wednesday", "wednesday"] }
    ]
  },
  {
    id: 't10_07',
    question: "All-Time Top Scorers in FIFA World Cup History",
    answers: [
      { name: "Miroslav Klose", value: "16 goals", accepts: ["miroslav klose", "klose"] },
      { name: "Ronaldo Nazário", value: "15 goals", accepts: ["ronaldo nazario", "ronaldo", "r9"] },
      { name: "Gerd Müller", value: "14 goals", accepts: ["gerd muller", "muller", "gerd müller", "müller"] },
      { name: "Just Fontaine", value: "13 goals", accepts: ["just fontaine", "fontaine"] },
      { name: "Lionel Messi", value: "13 goals", accepts: ["lionel messi", "messi", "leo messi"] },
      { name: "Pelé", value: "12 goals", accepts: ["pele", "pelé"] },
      { name: "Sándor Kocsis", value: "11 goals", accepts: ["sandor kocsis", "kocsis", "sándor kocsis"] },
      { name: "Jürgen Klinsmann", value: "11 goals", accepts: ["jurgen klinsmann", "klinsmann", "jürgen klinsmann"] },
      { name: "Kylian Mbappé", value: "12 goals", accepts: ["kylian mbappe", "mbappe", "mbappé"] },
      { name: "Gary Lineker", value: "10 goals", accepts: ["gary lineker", "lineker"] }
    ]
  },
  {
    id: 't10_08',
    question: "All-Time Top Goalscorers for the Brazil National Team",
    answers: [
      { name: "Neymar", value: "79 goals", accepts: ["ney", "neymar", "neymar jr"] },
      { name: "Pelé", value: "77 goals", accepts: ["pele", "pelé"] },
      { name: "Ronaldo Nazário", value: "62 goals", accepts: ["ronaldo nazario", "ronaldo", "r9"] },
      { name: "Romário", value: "55 goals", accepts: ["romario", "romário"] },
      { name: "Zico", value: "48 goals", accepts: ["zico"] },
      { name: "Bebeto", value: "39 goals", accepts: ["bebeto"] },
      { name: "Rivaldo", value: "35 goals", accepts: ["rivaldo"] },
      { name: "Jairzinho", value: "33 goals", accepts: ["jairzinho"] },
      { name: "Ronaldinho", value: "33 goals", accepts: ["ronaldinho", "ronaldinho gaucho"] },
      { name: "Ademir", value: "32 goals", accepts: ["ademir"] }
    ]
  },
  {
    id: 't10_09',
    question: "All-Time Top Scorers in UEFA Champions League History (as of mid-2026)",
    answers: [
      { name: "Cristiano Ronaldo", value: "140 goals", accepts: ["cristiano ronaldo", "ronaldo", "cr7"] },
      { name: "Lionel Messi", value: "129 goals", accepts: ["lionel messi", "messi", "leo messi"] },
      { name: "Robert Lewandowski", value: "109 goals", accepts: ["robert lewandowski", "lewandowski", "lewa"] },
      { name: "Karim Benzema", value: "90 goals", accepts: ["karim benzema", "benzema"] },
      { name: "Raúl", value: "71 goals", accepts: ["raul", "raúl", "raul gonzalez"] },
      { name: "Kylian Mbappé", value: "70 goals", accepts: ["kylian mbappe", "mbappe", "mbappé"] },
      { name: "Erling Haaland", value: "57 goals", accepts: ["erling haaland", "haaland"] },
      { name: "Thomas Müller", value: "57 goals", accepts: ["thomas muller", "muller", "thomas müller", "müller"] },
      { name: "Ruud van Nistelrooy", value: "56 goals", accepts: ["ruud van nistelrooy", "van nistelrooy"] },
      { name: "Harry Kane", value: "54 goals", accepts: ["harry kane", "kane"] }
    ]
  },
  {
    id: 't10_10',
    question: "Deloitte Football Money League 2026: Highest Revenue-Generating Clubs",
    answers: [
      { name: "Real Madrid", value: "€1,161m", accepts: ["real madrid", "madrid"] },
      { name: "Barcelona", value: "€974.8m", accepts: ["barcelona", "barca"] },
      { name: "Bayern Munich", value: "€860.6m", accepts: ["bayern munich", "bayern", "munich"] },
      { name: "Paris Saint-Germain", value: "€837m", accepts: ["paris saint-germain", "psg", "paris"] },
      { name: "Liverpool", value: "€836.1m", accepts: ["liverpool"] },
      { name: "Manchester City", value: "€829.3m", accepts: ["manchester city", "man city", "city"] },
      { name: "Arsenal", value: "€821.7m", accepts: ["arsenal"] },
      { name: "Manchester United", value: "€793.1m", accepts: ["manchester united", "man utd", "man united"] },
      { name: "Tottenham Hotspur", value: "€672.6m", accepts: ["tottenham hotspur", "tottenham", "spurs"] },
      { name: "Chelsea", value: "€584.1m", accepts: ["chelsea"] }
    ]
  },
  {
    id: 't10_11',
    question: "Premier League All-Time Top Assist Providers",
    answers: [
      { name: "Ryan Giggs", value: "162 assists", accepts: ["ryan giggs", "giggs"] },
      { name: "Kevin De Bruyne", value: "119 assists", accepts: ["kevin de bruyne", "de bruyne", "kdb"] },
      { name: "Cesc Fàbregas", value: "111 assists", accepts: ["cesc fabregas", "fabregas", "cesc fàbregas", "fàbregas"] },
      { name: "Wayne Rooney", value: "103 assists", accepts: ["wayne rooney", "rooney"] },
      { name: "Frank Lampard", value: "102 assists", accepts: ["frank lampard", "lampard"] },
      { name: "Dennis Bergkamp", value: "94 assists", accepts: ["dennis bergkamp", "bergkamp"] },
      { name: "Mohamed Salah", value: "94 assists", accepts: ["mohamed salah", "salah", "mo salah"] },
      { name: "David Silva", value: "93 assists", accepts: ["david silva", "silva"] },
      { name: "Steven Gerrard", value: "92 assists", accepts: ["steven gerrard", "gerrard"] },
      { name: "James Milner", value: "90 assists", accepts: ["james milner", "milner"] }
    ]
  },
  {
    id: 't10_12',
    question: "Clubs with the Most English League Cup (EFL/Carabao Cup) Titles",
    answers: [
      { name: "Liverpool", value: "10 titles", accepts: ["liverpool"] },
      { name: "Manchester City", value: "9 titles", accepts: ["manchester city", "man city", "city"] },
      { name: "Manchester United", value: "6 titles", accepts: ["manchester united", "man utd", "man united"] },
      { name: "Aston Villa", value: "5 titles", accepts: ["aston villa", "villa"] },
      { name: "Chelsea", value: "5 titles", accepts: ["chelsea"] },
      { name: "Tottenham Hotspur", value: "4 titles", accepts: ["tottenham hotspur", "tottenham", "spurs"] },
      { name: "Nottingham Forest", value: "4 titles", accepts: ["nottingham forest", "forest"] },
      { name: "Leicester City", value: "3 titles", accepts: ["leicester city", "leicester"] },
      { name: "Birmingham City", value: "2 titles", accepts: ["birmingham city", "birmingham"] },
      { name: "Arsenal", value: "2 titles", accepts: ["arsenal"] }
    ]
  },
  {
    id: 't10_13',
    question: "All-Time Top Goalscorers for the Argentina National Team",
    answers: [
      { name: "Lionel Messi", value: "125 goals", accepts: ["lionel messi", "messi", "leo messi"] },
      { name: "Gabriel Batistuta", value: "56 goals", accepts: ["gabriel batistuta", "batistuta", "batigol"] },
      { name: "Sergio Agüero", value: "42 goals", accepts: ["sergio aguero", "aguero", "sergio agüero", "agüero", "kun aguero"] },
      { name: "Hernán Crespo", value: "35 goals", accepts: ["hernan crespo", "crespo", "hernán crespo"] },
      { name: "Diego Maradona", value: "34 goals", accepts: ["diego maradona", "maradona"] },
      { name: "Lautaro Martínez", value: "30+ goals", accepts: ["lautaro martinez", "lautaro", "martinez", "lautaro martínez"] },
      { name: "Luis Artime", value: "24 goals", accepts: ["luis artime", "artime"] },
      { name: "Daniel Passarella", value: "20 goals", accepts: ["daniel passarella", "passarella"] },
      { name: "José Sanfilippo", value: "18 goals", accepts: ["jose sanfilippo", "sanfilippo", "josé sanfilippo"] },
      { name: "Ángel Labruna", value: "17 goals", accepts: ["angel labruna", "labruna", "ángel labruna"] }
    ]
  },
  {
    id: 't10_14',
    question: "Countries with the Most UEFA European Championship (Euro) Titles",
    answers: [
      { name: "Spain", value: "4 titles", accepts: ["spain"] },
      { name: "Germany", value: "3 titles", accepts: ["germany", "west germany"] },
      { name: "France", value: "2 titles", accepts: ["france"] },
      { name: "Italy", value: "2 titles", accepts: ["italy"] },
      { name: "Soviet Union", value: "1 title", accepts: ["soviet union", "ussr"] },
      { name: "Czechoslovakia", value: "1 title", accepts: ["czechoslovakia"] },
      { name: "Netherlands", value: "1 title", accepts: ["netherlands", "holland"] },
      { name: "Denmark", value: "1 title", accepts: ["denmark"] },
      { name: "Greece", value: "1 title", accepts: ["greece"] },
      { name: "Portugal", value: "1 title", accepts: ["portugal"] }
    ]
  },
  {
    id: 't10_15',
    question: "Clubs with the Most FA Cup Titles (mid-2026)",
    answers: [
      { name: "Arsenal", value: "14 titles", accepts: ["arsenal"] },
      { name: "Manchester United", value: "13 titles", accepts: ["manchester united", "man utd", "man united"] },
      { name: "Chelsea", value: "8 titles", accepts: ["chelsea"] },
      { name: "Liverpool", value: "8 titles", accepts: ["liverpool"] },
      { name: "Tottenham Hotspur", value: "8 titles", accepts: ["tottenham hotspur", "tottenham", "spurs"] },
      { name: "Manchester City", value: "8 titles", accepts: ["manchester city", "man city", "city"] },
      { name: "Aston Villa", value: "7 titles", accepts: ["aston villa", "villa"] },
      { name: "Newcastle United", value: "6 titles", accepts: ["newcastle united", "newcastle"] },
      { name: "Blackburn Rovers", value: "6 titles", accepts: ["blackburn rovers", "blackburn"] },
      { name: "Everton", value: "5 titles", accepts: ["everton"] }
    ]
  }
];